extern crate rustc_hir;
extern crate rustc_lint;
extern crate rustc_middle;
extern crate rustc_span;

use std::collections::{HashMap, HashSet};

use rustc_hir::{Item, ItemKind};
use rustc_lint::LateContext;
use rustc_middle::ty::{self, Ty};
use rustc_span::def_id::LocalDefId;
use rustc_span::{Span, Symbol};

// -----------------------------------------------------------------------------
// Bon: Authored and generated construction contracts
// -----------------------------------------------------------------------------

/// Authored struct information relevant to Bon construction policy.
#[derive(Clone)]
pub struct BonStructContract {
    /// Struct name receiving construction diagnostics.
    pub span: Span,
    /// Authored struct name.
    pub name: Symbol,
    /// Whether at least one field is hidden behind the type's constructor API.
    pub has_restricted_fields: bool,
}

/// Authored structs and generated types correlated across macro expansion.
#[derive(Default)]
pub struct BonContractCatalog {
    /// Authored struct contracts indexed by local definition.
    structs: HashMap<LocalDefId, BonStructContract>,
    /// Authored structs known to derive `bon::Builder`.
    derived: HashSet<LocalDefId>,
    /// All local types emitted by Bon expansions.
    generated_types: HashSet<LocalDefId>,
    /// Generated types that represent unfinished builder state.
    generated_builders: HashSet<LocalDefId>,
}

impl BonContractCatalog {
    /// Returns whether a field is less visible than the struct that owns it.
    fn field_is_restricted(cx: &LateContext<'_>, owner: LocalDefId, field: LocalDefId) -> bool {
        let owner_visibility = cx.tcx.visibility(owner);
        let field_visibility = cx.tcx.visibility(field);
        match owner_visibility {
            ty::Visibility::Public => !field_visibility.is_public(),
            ty::Visibility::Restricted(scope) => {
                !field_visibility.is_accessible_from(scope, cx.tcx)
            }
        }
    }

    /// Returns whether a span was generated by Bon's procedural macros.
    fn is_bon_expansion(cx: &LateContext<'_>, span: Span) -> bool {
        span.macro_backtrace().any(|expansion| {
            expansion.macro_def_id.is_some_and(|definition| {
                cx.tcx.crate_name(definition.krate).as_str() == "bon_macros"
            })
        })
    }

    /// Returns whether a span belongs specifically to Bon's `Builder` derive.
    fn is_builder_expansion(cx: &LateContext<'_>, span: Span) -> bool {
        span.macro_backtrace().any(|expansion| {
            expansion.macro_def_id.is_some_and(|definition| {
                cx.tcx.crate_name(definition.krate).as_str() == "bon_macros"
                    && cx.tcx.item_name(definition).as_str() == "Builder"
            })
        })
    }

    /// Returns an authored struct only when Bon generated its builder.
    pub fn derived_struct(&self, def_id: LocalDefId) -> Option<&BonStructContract> {
        self.derived
            .contains(&def_id)
            .then(|| self.structs.get(&def_id))
            .flatten()
    }

    /// Returns whether a definition is a Bon implementation detail.
    pub fn is_generated_type(&self, def_id: LocalDefId) -> bool {
        self.generated_types.contains(&def_id)
    }

    /// Finds a Bon builder nested anywhere in a resolved type.
    pub fn generated_builder_in_type(&self, ty: Ty<'_>) -> Option<LocalDefId> {
        match ty.kind() {
            ty::Adt(definition, arguments) => {
                let local = definition.did().as_local();

                // A directly generated builder is the nearest builder identity in this type.
                if local.is_some_and(|definition| self.generated_builders.contains(&definition)) {
                    return local;
                }
                arguments
                    .types()
                    .find_map(|nested| self.generated_builder_in_type(nested))
            }
            ty::Ref(_, nested, _)
            | ty::RawPtr(nested, _)
            | ty::Slice(nested)
            | ty::Array(nested, _) => self.generated_builder_in_type(*nested),
            ty::Tuple(elements) => elements
                .iter()
                .find_map(|nested| self.generated_builder_in_type(nested)),
            _ => None,
        }
    }

    /// Records generated Bon types and correlates derive impls with authored structs.
    fn record_generated_impl(&mut self, cx: &LateContext<'_>, item: &Item<'_>) {
        // Expansions unrelated to Bon cannot establish builder implementation details.
        if !Self::is_bon_expansion(cx, item.span) {
            return;
        }

        // Generated builder types can escape independently of their authored target.
        if matches!(item.kind, ItemKind::Struct(..) | ItemKind::Enum(..)) {
            self.generated_types.insert(item.owner_id.def_id);
            if item
                .kind
                .ident()
                .is_some_and(|identifier| identifier.name.as_str().ends_with("Builder"))
            {
                self.generated_builders.insert(item.owner_id.def_id);
            }
        }

        // Only Bon-generated builder implementations identify the authored derive target.
        if !matches!(item.kind, ItemKind::Impl(_)) || !Self::is_builder_expansion(cx, item.span) {
            return;
        }

        // Generated implementations without a local aggregate target cannot be correlated.
        let Some(definition) = cx
            .tcx
            .type_of(item.owner_id)
            .instantiate_identity()
            .ty_adt_def()
            .and_then(|definition| definition.did().as_local())
        else {
            return;
        };
        self.derived.insert(definition);
    }

    /// Records either generated expansion evidence or an authored struct contract.
    pub fn check_item(&mut self, cx: &LateContext<'_>, item: &Item<'_>) {
        // Expanded items contribute generated Bon evidence rather than authored contracts.
        if item.span.from_expansion() {
            self.record_generated_impl(cx, item);
            return;
        }

        // Only authored structs can be targets of Bon's derive contract.
        let ItemKind::Struct(identifier, _, data) = item.kind else {
            return;
        };

        self.structs.insert(
            item.owner_id.def_id,
            BonStructContract {
                span: identifier.span,
                name: identifier.name,
                has_restricted_fields: data
                    .fields()
                    .iter()
                    .any(|field| Self::field_is_restricted(cx, item.owner_id.def_id, field.def_id)),
            },
        );
    }
}
