extern crate rustc_errors;
extern crate rustc_hir;
extern crate rustc_span;

use std::borrow::Cow;

use rustc_errors::DiagDecorator;
use rustc_hir::{FieldDef, HirId, ImplItem, Item, ItemKind, Node, TraitItem, Variant};
use rustc_lint::{LateContext, LateLintPass, LintContext};
use rustc_span::{Span, sym};

use crate::utils::diagnostic::LateViolation;
use crate::utils::source_provenance::is_build_generated;

// -----------------------------------------------------------------------------
// Violation: Undocumented declaration diagnostic
// -----------------------------------------------------------------------------

/// Authored semantic declaration with no documentation contract.
struct Violation {
    /// Declaration node used for item-level lint attributes.
    hir_id: HirId,
    /// Identifier or declaration extent receiving the diagnostic.
    span: Span,
    /// User-facing declaration kind.
    kind: &'static str,
}

impl Violation {
    /// Classifies an authored declaration only when its semantic contract is undocumented.
    fn from_declaration(
        cx: &LateContext<'_>,
        hir_id: HirId,
        span: Span,
        kind: &'static str,
    ) -> Option<Self> {
        if Self::has_documentation(cx, hir_id)
            || span.in_external_macro(cx.sess().source_map())
            || is_build_generated(cx, span)
        {
            return None;
        }
        Some(Self { hir_id, span, kind })
    }

    /// Returns whether an item carries any authored `doc` attribute or documentation comment.
    fn has_documentation(cx: &LateContext<'_>, hir_id: HirId) -> bool {
        cx.tcx
            .hir_attrs(hir_id)
            .iter()
            .any(|attribute| attribute.is_doc_comment().is_some() || attribute.has_name(sym::doc))
    }
}

impl LateViolation for Violation {
    fn primary_message(&self) -> Cow<'_, str> {
        Cow::Owned(format!("this {} is missing documentation", self.kind))
    }

    fn rationale_message(&self) -> Cow<'_, str> {
        Cow::Owned(format!(
            "without documentation, readers and agents must infer this {}'s purpose, invariants, and contract from implementation details",
            self.kind
        ))
    }

    fn remediation_message(&self) -> Cow<'_, str> {
        Cow::Borrowed("document its purpose, contract, or semantic role")
    }

    fn emit(self, cx: &LateContext<'_>) {
        cx.tcx.emit_node_span_lint(
            UNDOCUMENTED_ITEMS,
            self.hir_id,
            self.span,
            DiagDecorator(|diag| {
                diag.primary_message(self.primary_message().into_owned());
                diag.note(self.rationale_message().into_owned());
                diag.help(self.remediation_message().into_owned());
            }),
        );
    }
}

// -----------------------------------------------------------------------------
// UndocumentedItems: Lint pass
// -----------------------------------------------------------------------------

/// Late lint pass that requires semantic declarations to explain their public and internal roles.
struct UndocumentedItems;

dylint_linting::impl_late_lint! {
    /// ### What it does
    ///
    /// Requires documentation on authored types, fields, enum variants, traits, constants,
    /// statics, free functions, trait items, and inherent implementation items regardless of
    /// visibility. Modules, imports, re-exports, implementation blocks, and foreign declarations
    /// are intentionally excluded.
    ///
    /// Items generated by external macros are also excluded because their source belongs to the
    /// dependency that defined the macro. Items from local macros remain subject to the rule.
    ///
    /// ### Why is this bad?
    ///
    /// Names describe identity, but they rarely capture contracts, invariants, ownership, or the
    /// reason a declaration exists. Requiring documentation for internal helpers as well as public
    /// APIs keeps those decisions available to reviewers and coding agents instead of forcing them
    /// to reconstruct intent from implementation details.
    ///
    /// For example, these declarations leave their relationship and field semantics implicit:
    ///
    /// ```rust
    /// struct RetryPolicy {
    ///     attempts: usize,
    /// }
    ///
    /// fn retry(policy: &RetryPolicy) {}
    /// ```
    ///
    /// Document each semantic declaration where its contract is defined:
    ///
    /// ```rust
    /// /// Limits repeated attempts after transient failures.
    /// struct RetryPolicy {
    ///     /// Maximum number of attempts, including the initial request.
    ///     attempts: usize,
    /// }
    ///
    /// /// Runs an operation according to the supplied retry policy.
    /// fn retry(policy: &RetryPolicy) {}
    /// ```
    ///
    /// Module declarations are omitted deliberately so barrel files can remain concise maps of
    /// the source tree. Trait implementations are omitted because their contracts belong on the
    /// trait and its items; inherent methods must carry their own documentation.
    pub UNDOCUMENTED_ITEMS,
    Warn,
    "requires documentation for semantic declarations while leaving barrel modules clean",
    UndocumentedItems
}

impl UndocumentedItems {
    /// Classifies module-level declarations governed by this rule.
    fn item_kind(item: &Item<'_>) -> Option<&'static str> {
        Self::type_item_kind(item).or_else(|| Self::value_item_kind(item))
    }

    /// Classifies documented nominal type declarations.
    fn type_item_kind(item: &Item<'_>) -> Option<&'static str> {
        Self::concrete_type_item_kind(item).or_else(|| Self::abstract_type_item_kind(item))
    }

    /// Classifies concrete nominal declarations.
    const fn concrete_type_item_kind(item: &Item<'_>) -> Option<&'static str> {
        match item.kind {
            ItemKind::Enum(..) => Some("enum"),
            ItemKind::Struct(..) => Some("struct"),
            ItemKind::Union(..) => Some("union"),
            _ => None,
        }
    }

    /// Classifies abstract nominal declarations.
    const fn abstract_type_item_kind(item: &Item<'_>) -> Option<&'static str> {
        match item.kind {
            ItemKind::Trait(..) => Some("trait"),
            ItemKind::TraitAlias(..) => Some("trait alias"),
            ItemKind::TyAlias(..) => Some("type alias"),
            _ => None,
        }
    }

    /// Classifies documented value-level declarations.
    const fn value_item_kind(item: &Item<'_>) -> Option<&'static str> {
        match item.kind {
            ItemKind::Const(..) => Some("constant"),
            ItemKind::Fn { .. } => Some("function"),
            ItemKind::Static(..) => Some("static"),
            _ => None,
        }
    }

    /// Returns the identifier span for a named module-level declaration.
    fn item_span(item: &Item<'_>) -> Span {
        item.kind
            .ident()
            .map_or(item.span, |identifier| identifier.span)
    }

    /// Returns whether an associated item belongs to a trait implementation.
    fn is_trait_implementation_item(cx: &LateContext<'_>, item: &ImplItem<'_>) -> bool {
        // Resolve the associated item's owning HIR declaration.
        let parent = cx.tcx.local_parent(item.owner_id.def_id);
        let parent_node = cx.tcx.hir_node_by_def_id(parent);

        // Resolve the enclosing item and its implementation declaration.
        let Node::Item(parent_item) = parent_node else {
            return false;
        };
        let ItemKind::Impl(implementation) = parent_item.kind else {
            return false;
        };

        // Exclude associated items implementing an external trait contract.
        implementation.of_trait.is_some()
    }
}

impl<'tcx> LateLintPass<'tcx> for UndocumentedItems {
    fn check_item(&mut self, cx: &LateContext<'tcx>, item: &'tcx Item<'tcx>) {
        let Some(kind) = Self::item_kind(item) else {
            return;
        };
        let Some(violation) =
            Violation::from_declaration(cx, item.hir_id(), Self::item_span(item), kind)
        else {
            return;
        };
        violation.emit(cx);
    }

    fn check_field_def(&mut self, cx: &LateContext<'tcx>, field: &'tcx FieldDef<'tcx>) {
        let span = if field.is_positional() {
            field.span
        } else {
            field.ident.span
        };
        let Some(violation) = Violation::from_declaration(cx, field.hir_id, span, "field") else {
            return;
        };
        violation.emit(cx);
    }

    fn check_variant(&mut self, cx: &LateContext<'tcx>, variant: &'tcx Variant<'tcx>) {
        let Some(violation) =
            Violation::from_declaration(cx, variant.hir_id, variant.ident.span, "enum variant")
        else {
            return;
        };
        violation.emit(cx);
    }

    fn check_trait_item(&mut self, cx: &LateContext<'tcx>, item: &'tcx TraitItem<'tcx>) {
        let Some(violation) =
            Violation::from_declaration(cx, item.hir_id(), item.ident.span, "trait item")
        else {
            return;
        };
        violation.emit(cx);
    }

    fn check_impl_item(&mut self, cx: &LateContext<'tcx>, item: &'tcx ImplItem<'tcx>) {
        if Self::is_trait_implementation_item(cx, item) {
            return;
        }
        let Some(violation) =
            Violation::from_declaration(cx, item.hir_id(), item.ident.span, "inherent impl item")
        else {
            return;
        };
        violation.emit(cx);
    }
}
