extern crate rustc_errors;
extern crate rustc_hir;
extern crate rustc_span;

use rustc_errors::DiagDecorator;
use rustc_hir::{FieldDef, HirId, ImplItem, Item, ItemKind, Node, TraitItem, Variant};
use rustc_lint::{LateContext, LateLintPass, LintContext};
use rustc_span::{Span, sym};

// -----------------------------------------------------------------------------
// UndocumentedItems
// -----------------------------------------------------------------------------

/// Late lint pass that requires semantic declarations to explain their public and internal roles.
struct UndocumentedItems;

dylint_linting::impl_late_lint! {
    /// ### What it does
    ///
    /// Requires documentation on authored types, fields, enum variants, traits, constants,
    /// statics, free functions, trait items, and inherent implementation items regardless of
    /// visibility. Modules, imports, re-exports, implementation blocks, and foreign declarations
    /// are intentionally excluded.
    ///
    /// Items generated by external macros are also excluded because their source belongs to the
    /// dependency that defined the macro. Items from local macros remain subject to the rule.
    ///
    /// ### Why is this bad?
    ///
    /// Names describe identity, but they rarely capture contracts, invariants, ownership, or the
    /// reason a declaration exists. Requiring documentation for internal helpers as well as public
    /// APIs keeps those decisions available to reviewers and coding agents instead of forcing them
    /// to reconstruct intent from implementation details.
    ///
    /// For example, these declarations leave their relationship and field semantics implicit:
    ///
    /// ```rust
    /// struct RetryPolicy {
    ///     attempts: usize,
    /// }
    ///
    /// fn retry(policy: &RetryPolicy) {}
    /// ```
    ///
    /// Document each semantic declaration where its contract is defined:
    ///
    /// ```rust
    /// /// Limits repeated attempts after transient failures.
    /// struct RetryPolicy {
    ///     /// Maximum number of attempts, including the initial request.
    ///     attempts: usize,
    /// }
    ///
    /// /// Runs an operation according to the supplied retry policy.
    /// fn retry(policy: &RetryPolicy) {}
    /// ```
    ///
    /// Module declarations are omitted deliberately so barrel files can remain concise maps of
    /// the source tree. Trait implementations are omitted because their contracts belong on the
    /// trait and its items; inherent methods must carry their own documentation.
    pub UNDOCUMENTED_ITEMS,
    Warn,
    "requires documentation for semantic declarations while leaving barrel modules clean",
    UndocumentedItems
}

impl UndocumentedItems {
    /// Returns whether an item carries any authored `doc` attribute or documentation comment.
    fn has_documentation(cx: &LateContext<'_>, hir_id: HirId) -> bool {
        cx.tcx
            .hir_attrs(hir_id)
            .iter()
            .any(|attribute| attribute.is_doc_comment().is_some() || attribute.has_name(sym::doc))
    }

    /// Returns whether a source span is controlled by the crate being linted.
    fn is_authored(cx: &LateContext<'_>, span: Span) -> bool {
        !span.in_external_macro(cx.sess().source_map())
    }

    /// Emits one declaration-focused documentation diagnostic.
    fn emit(cx: &LateContext<'_>, hir_id: HirId, span: Span, kind: &str) {
        if Self::has_documentation(cx, hir_id) || !Self::is_authored(cx, span) {
            return;
        }
        cx.tcx.emit_node_span_lint(
            UNDOCUMENTED_ITEMS,
            hir_id,
            span,
            DiagDecorator(|diag| {
                diag.primary_message(format!("this {kind} is missing documentation"));
                diag.help("document its purpose, contract, or semantic role");
            }),
        );
    }

    /// Classifies module-level declarations governed by this rule.
    const fn item_kind(item: &Item<'_>) -> Option<&'static str> {
        match item.kind {
            ItemKind::Const(..) => Some("constant"),
            ItemKind::Enum(..) => Some("enum"),
            ItemKind::Fn { .. } => Some("function"),
            ItemKind::Static(..) => Some("static"),
            ItemKind::Struct(..) => Some("struct"),
            ItemKind::Trait(..) => Some("trait"),
            ItemKind::TraitAlias(..) => Some("trait alias"),
            ItemKind::TyAlias(..) => Some("type alias"),
            ItemKind::Union(..) => Some("union"),
            _ => None,
        }
    }

    /// Returns the identifier span for a named module-level declaration.
    fn item_span(item: &Item<'_>) -> Span {
        item.kind
            .ident()
            .map_or(item.span, |identifier| identifier.span)
    }

    /// Returns whether an associated item belongs to a trait implementation.
    fn is_trait_implementation_item(cx: &LateContext<'_>, item: &ImplItem<'_>) -> bool {
        let parent = cx.tcx.local_parent(item.owner_id.def_id);
        matches!(
            cx.tcx.hir_node_by_def_id(parent),
            Node::Item(Item {
                kind: ItemKind::Impl(implementation),
                ..
            }) if implementation.of_trait.is_some()
        )
    }
}

impl<'tcx> LateLintPass<'tcx> for UndocumentedItems {
    fn check_item(&mut self, cx: &LateContext<'tcx>, item: &'tcx Item<'tcx>) {
        let Some(kind) = Self::item_kind(item) else {
            return;
        };
        Self::emit(cx, item.hir_id(), Self::item_span(item), kind);
    }

    fn check_field_def(&mut self, cx: &LateContext<'tcx>, field: &'tcx FieldDef<'tcx>) {
        let span = if field.is_positional() {
            field.span
        } else {
            field.ident.span
        };
        Self::emit(cx, field.hir_id, span, "field");
    }

    fn check_variant(&mut self, cx: &LateContext<'tcx>, variant: &'tcx Variant<'tcx>) {
        Self::emit(cx, variant.hir_id, variant.ident.span, "enum variant");
    }

    fn check_trait_item(&mut self, cx: &LateContext<'tcx>, item: &'tcx TraitItem<'tcx>) {
        Self::emit(cx, item.hir_id(), item.ident.span, "trait item");
    }

    fn check_impl_item(&mut self, cx: &LateContext<'tcx>, item: &'tcx ImplItem<'tcx>) {
        if Self::is_trait_implementation_item(cx, item) {
            return;
        }
        Self::emit(cx, item.hir_id(), item.ident.span, "inherent impl item");
    }
}
