extern crate rustc_errors;
extern crate rustc_hir;
extern crate rustc_middle;
extern crate rustc_span;

use std::borrow::Cow;

use rustc_errors::DiagDecorator;
use rustc_hir::{FieldDef, FnRetTy, ImplItem, ImplItemKind, Item, ItemKind};
use rustc_lint::{LateContext, LateLintPass, LintContext};
use rustc_middle::ty::{self, Ty};
use rustc_span::Span;
use rustc_span::def_id::LocalDefId;

use super::contracts::BonContractCatalog;
use crate::utils::diagnostic::LateViolation;

// -----------------------------------------------------------------------------
// Violation: Generated Bon type in a public signature
// -----------------------------------------------------------------------------

/// Public boundary coupled to Bon's generated typestate representation.
struct Violation {
    /// Public type occurrence receiving the diagnostic.
    span: Span,
    /// Authored spelling of the generated type.
    ty: String,
}

impl LateViolation for Violation {
    fn primary_message(&self) -> Cow<'_, str> {
        Cow::Owned(format!(
            "public API exposes generated Bon implementation type `{}`",
            self.ty
        ))
    }

    fn rationale_message(&self) -> Cow<'_, str> {
        Cow::Borrowed(
            "naming a generated builder or typestate type couples callers to macro representation and required-member encoding",
        )
    }

    fn remediation_message(&self) -> Cow<'_, str> {
        Cow::Borrowed(
            "return or accept the completed domain value, or define an intentional named partial-application abstraction",
        )
    }

    fn emit(self, cx: &LateContext<'_>) {
        cx.emit_span_lint(
            BON_PUBLIC_BUILDER_IMPLEMENTATION_TYPES,
            self.span,
            DiagDecorator(|diag| {
                diag.primary_message(self.primary_message().into_owned());
                diag.span_label(self.span, "this type is generated by Bon");
                diag.note(self.rationale_message().into_owned());
                diag.help(self.remediation_message().into_owned());
            }),
        );
    }
}

// -----------------------------------------------------------------------------
// Exposure: Resolved public type evidence
// -----------------------------------------------------------------------------

/// Named type found within a public input, output, or field.
struct Exposure {
    /// Public type syntax containing the named definition.
    span: Span,
    /// Resolved local type definition.
    definition: LocalDefId,
    /// Source spelling used in the diagnostic.
    ty: String,
}

/// Recursively records named definitions nested in one public type.
fn exposure_collect_definitions(
    cx: &LateContext<'_>,
    ty: Ty<'_>,
    span: Span,
    exposures: &mut Vec<Exposure>,
) {
    match ty.kind() {
        ty::Adt(definition, arguments) => {
            if let Some(definition) = definition.did().as_local() {
                let spelling = cx
                    .sess()
                    .source_map()
                    .span_to_snippet(span)
                    .unwrap_or_else(|_| cx.tcx.item_name(definition.to_def_id()).to_string());

                exposures.push(Exposure {
                    span,
                    definition,
                    ty: spelling,
                });
            }
            for nested in arguments.types() {
                exposure_collect_definitions(cx, nested, span, exposures);
            }
        }
        ty::Ref(_, nested, _) | ty::Slice(nested) => {
            exposure_collect_definitions(cx, *nested, span, exposures);
        }
        ty::Array(nested, _) => exposure_collect_definitions(cx, *nested, span, exposures),
        ty::Tuple(elements) => {
            for nested in *elements {
                exposure_collect_definitions(cx, nested, span, exposures);
            }
        }
        _ => {}
    }
}

// -----------------------------------------------------------------------------
// BonPublicBuilderImplementationTypes: Public representation policy
// -----------------------------------------------------------------------------

/// Correlates public signature types with Bon-generated definitions.
#[derive(Default)]
struct BonPublicBuilderImplementationTypes {
    /// Generated Bon definitions recognized in the crate.
    catalog: BonContractCatalog,
    /// Named types collected from public boundaries.
    exposures: Vec<Exposure>,
}

dylint_linting::impl_late_lint! {
    #[doc = include_str!("README.md")]
    pub BON_PUBLIC_BUILDER_IMPLEMENTATION_TYPES,
    Warn,
    "rejects generated Bon implementation types in public APIs",
    BonPublicBuilderImplementationTypes::default()
}

impl<'tcx> LateLintPass<'tcx> for BonPublicBuilderImplementationTypes {
    fn check_item(&mut self, cx: &LateContext<'tcx>, item: &'tcx Item<'tcx>) {
        self.catalog.check_item(cx, item);
        if item.span.from_expansion() || !cx.tcx.visibility(item.owner_id.def_id).is_public() {
            return;
        }
        let ItemKind::Fn { sig, .. } = item.kind else {
            return;
        };
        self.collect_decl(cx, item.owner_id.def_id, sig.decl);
    }

    fn check_impl_item(&mut self, cx: &LateContext<'tcx>, item: &'tcx ImplItem<'tcx>) {
        if item.span.from_expansion() || !cx.tcx.visibility(item.owner_id.def_id).is_public() {
            return;
        }
        let ImplItemKind::Fn(signature, _) = item.kind else {
            return;
        };
        self.collect_decl(cx, item.owner_id.def_id, signature.decl);
    }

    fn check_field_def(&mut self, cx: &LateContext<'tcx>, field: &'tcx FieldDef<'tcx>) {
        if field.span.from_expansion() || !cx.tcx.visibility(field.def_id).is_public() {
            return;
        }
        let ty = cx.tcx.type_of(field.def_id).instantiate_identity();
        self.collect_ty(cx, ty, field.ty.span);
    }

    fn check_crate_post(&mut self, cx: &LateContext<'tcx>) {
        for exposure in &self.exposures {
            if !(self.catalog.is_generated_type(exposure.definition)) {
                continue;
            }
            Violation {
                span: exposure.span,
                ty: exposure.ty.clone(),
            }
            .emit(cx);
        }
    }
}

impl BonPublicBuilderImplementationTypes {
    /// Adds every named definition nested in one public type.
    fn collect_ty(&mut self, cx: &LateContext<'_>, ty: Ty<'_>, span: Span) {
        exposure_collect_definitions(cx, ty, span, &mut self.exposures);
    }

    /// Collects named types from every input and the explicit return type.
    fn collect_decl<'tcx>(
        &mut self,
        cx: &LateContext<'tcx>,
        def_id: LocalDefId,
        declaration: &'tcx rustc_hir::FnDecl<'tcx>,
    ) {
        let signature = cx.tcx.fn_sig(def_id).instantiate_identity().skip_binder();
        for (input, semantic) in declaration.inputs.iter().zip(signature.inputs()) {
            self.collect_ty(cx, *semantic, input.span);
        }
        let FnRetTy::Return(output) = declaration.output else {
            return;
        };
        self.collect_ty(cx, signature.output(), output.span);
    }
}
