extern crate rustc_errors;
extern crate rustc_hir;
extern crate rustc_middle;
extern crate rustc_span;

use std::borrow::Cow;

use rustc_errors::DiagDecorator;
use rustc_hir::{FieldDef, FnRetTy, ImplItem, ImplItemKind, Item, ItemKind};
use rustc_lint::{LateContext, LateLintPass, LintContext};
use rustc_middle::ty::{self, Ty};
use rustc_span::Span;
use rustc_span::def_id::LocalDefId;

use super::utils::contracts::BonContractCatalog;
use crate::utils::diagnostic::LateViolation;

// -----------------------------------------------------------------------------
// Violation: Generated Bon type in a public signature
// -----------------------------------------------------------------------------

/// Public boundary coupled to Bon's generated typestate representation.
struct Violation {
    /// Public type occurrence receiving the diagnostic.
    span: Span,
    /// Authored spelling of the generated type.
    ty: String,
}

impl LateViolation for Violation {
    fn primary_message(&self) -> Cow<'_, str> {
        Cow::Owned(format!(
            "public API exposes generated Bon implementation type `{}`",
            self.ty
        ))
    }

    fn rationale_message(&self) -> Cow<'_, str> {
        Cow::Borrowed(
            "naming a generated builder or typestate type couples callers to macro representation and required-member encoding",
        )
    }

    fn remediation_message(&self) -> Cow<'_, str> {
        Cow::Borrowed(
            "return or accept the completed domain value, or define an intentional named partial-application abstraction",
        )
    }

    fn emit(self, cx: &LateContext<'_>) {
        cx.emit_span_lint(
            BON_PUBLIC_BUILDER_IMPLEMENTATION_TYPES,
            self.span,
            DiagDecorator(|diag| {
                diag.primary_message(self.primary_message().into_owned());
                diag.span_label(self.span, "this type is generated by Bon");
                diag.note(self.rationale_message().into_owned());
                diag.help(self.remediation_message().into_owned());
            }),
        );
    }
}

// -----------------------------------------------------------------------------
// Exposure: Resolved public type evidence
// -----------------------------------------------------------------------------

/// Named type found within a public input, output, or field.
struct Exposure {
    /// Public type syntax containing the named definition.
    span: Span,
    /// Resolved local type definition.
    definition: LocalDefId,
    /// Source spelling used in the diagnostic.
    ty: String,
}

// -----------------------------------------------------------------------------
// BonPublicBuilderImplementationTypes: Public representation policy
// -----------------------------------------------------------------------------

/// Correlates public signature types with Bon-generated definitions.
#[derive(Default)]
struct BonPublicBuilderImplementationTypes {
    /// Generated Bon definitions recognized in the crate.
    catalog: BonContractCatalog,
    /// Named types collected from public boundaries.
    exposures: Vec<Exposure>,
}

crate::impl_late_lint! {
    #[doc = include_str!("README.md")]
    pub BON_PUBLIC_BUILDER_IMPLEMENTATION_TYPES,
    Warn,
    "rejects generated Bon implementation types in public APIs",
    BonPublicBuilderImplementationTypes::default()
}

impl BonPublicBuilderImplementationTypes {
    /// Records a named aggregate and recursively visits its generic arguments.
    fn collect_aggregate(
        cx: &LateContext<'_>,
        ty: Ty<'_>,
        span: Span,
        exposures: &mut Vec<Exposure>,
    ) {
        // Non-aggregate types contain no named implementation type or aggregate arguments.
        let ty::Adt(definition, arguments) = ty.kind() else {
            return;
        };
        if let Some(definition) = definition.did().as_local() {
            let spelling = cx
                .sess()
                .source_map()
                .span_to_snippet(span)
                .unwrap_or_else(|_| cx.tcx.item_name(definition.to_def_id()).to_string());

            exposures.push(Exposure {
                span,
                definition,
                ty: spelling,
            });
        }
        for nested in arguments.types() {
            Self::collect_definitions(cx, nested, span, exposures);
        }
    }

    /// Recursively records named definitions nested in one public type.
    fn collect_definitions(
        cx: &LateContext<'_>,
        ty: Ty<'_>,
        span: Span,
        exposures: &mut Vec<Exposure>,
    ) {
        match ty.kind() {
            ty::Adt(..) => Self::collect_aggregate(cx, ty, span, exposures),
            ty::Ref(_, nested, _) | ty::RawPtr(nested, _) | ty::Slice(nested) => {
                Self::collect_definitions(cx, *nested, span, exposures);
            }
            ty::Array(nested, _) => Self::collect_definitions(cx, *nested, span, exposures),
            ty::Tuple(elements) => {
                for nested in *elements {
                    Self::collect_definitions(cx, nested, span, exposures);
                }
            }
            _ => {}
        }
    }
}

impl<'tcx> LateLintPass<'tcx> for BonPublicBuilderImplementationTypes {
    fn check_item(&mut self, cx: &LateContext<'tcx>, item: &'tcx Item<'tcx>) {
        self.catalog.check_item(cx, item);

        // Generated or crate-private items cannot leak implementation types through public API.
        if item.span.from_expansion()
            || !cx
                .tcx
                .effective_visibilities(())
                .is_exported(item.owner_id.def_id)
        {
            return;
        }

        // Only functions expose signature types through this item callback.
        let ItemKind::Fn { sig, .. } = item.kind else {
            return;
        };
        self.collect_decl(cx, item.owner_id.def_id, sig.decl);
    }

    fn check_impl_item(&mut self, cx: &LateContext<'tcx>, item: &'tcx ImplItem<'tcx>) {
        // Generated or non-exported associated items cannot leak a public builder type.
        if item.span.from_expansion()
            || !cx
                .tcx
                .effective_visibilities(())
                .is_exported(item.owner_id.def_id)
        {
            return;
        }

        // Non-function associated items have no callable signature to inspect.
        let ImplItemKind::Fn(signature, _) = item.kind else {
            return;
        };
        self.collect_decl(cx, item.owner_id.def_id, signature.decl);
    }

    fn check_field_def(&mut self, cx: &LateContext<'tcx>, field: &'tcx FieldDef<'tcx>) {
        // Generated or non-exported fields do not expose their types through public API.
        if field.span.from_expansion()
            || !cx.tcx.effective_visibilities(()).is_exported(field.def_id)
        {
            return;
        }
        let ty = cx.tcx.type_of(field.def_id).instantiate_identity();
        self.collect_ty(cx, ty, field.ty.span);
    }

    fn check_crate_post(&mut self, cx: &LateContext<'tcx>) {
        for exposure in &self.exposures {
            if !(self.catalog.is_generated_type(exposure.definition)) {
                continue;
            }
            Violation {
                span: exposure.span,
                ty: exposure.ty.clone(),
            }
            .emit(cx);
        }
    }
}

impl BonPublicBuilderImplementationTypes {
    /// Adds every named definition nested in one public type.
    fn collect_ty(&mut self, cx: &LateContext<'_>, ty: Ty<'_>, span: Span) {
        Self::collect_definitions(cx, ty, span, &mut self.exposures);
    }

    /// Collects named types from every input and the explicit return type.
    fn collect_decl<'tcx>(
        &mut self,
        cx: &LateContext<'tcx>,
        def_id: LocalDefId,
        declaration: &'tcx rustc_hir::FnDecl<'tcx>,
    ) {
        let signature = cx.tcx.fn_sig(def_id).instantiate_identity().skip_binder();
        for (input, semantic) in declaration.inputs.iter().zip(signature.inputs()) {
            self.collect_ty(cx, *semantic, input.span);
        }

        // An implicit unit return contributes no authored output type to inspect.
        let FnRetTy::Return(output) = declaration.output else {
            return;
        };
        self.collect_ty(cx, signature.output(), output.span);
    }
}
