mod contracts;

pub mod derive_more_ambiguous_derived_error_sources;
pub mod derive_more_derived_constructors_bypassing_invariants;
pub mod derive_more_derived_conversions_bypassing_invariants;
pub mod derive_more_inconsistent_derived_equality;
pub mod derive_more_manual_conversion_impls;
pub mod derive_more_manual_constructors;
pub mod derive_more_manual_equality_impls;
pub mod derive_more_manual_error_impls;
pub mod derive_more_manual_forwarding_interfaces;
pub mod derive_more_manual_formatting_impls;
pub mod derive_more_manual_from_str_impls;
pub mod derive_more_manual_into_iterator_impls;
pub mod derive_more_mutable_forwarding_bypassing_invariants;
pub mod derive_more_non_roundtripping_derived_text_contracts;
pub mod derive_more_opaque_derived_display_contracts;
