// aux-build: external_macro.rs

#![feature(register_tool)]
#![allow(
    dead_code,
    misordered_inherent_impl_items,
    misordered_module_declarations,
    misordered_type_declarations,
    non_snake_case
)]
#![register_tool(rlib_lint)]

extern crate external_macro;

use external_macro::external_struct;

// A semantic boolean alias should be treated exactly like `bool`.
type Flag = bool;

// Named boolean fields without an accepted prefix should be reported.
struct Invalid {
    active: bool,
    visible: Flag,
}

// Accepted prefixes and non-boolean fields should not be reported.
struct Valid {
    is_active: bool,
    has_focus: Flag,
    r#is_ready: bool,
    count: usize,
}

// Prefix tokens without a predicate phrase should still be reported.
struct EmptyPredicate {
    is_: bool,
    has_: bool,
    is__active: bool,
}

// Tuple fields and fields belonging to enum variants are outside this lint's scope.
struct Tuple(bool);

enum NotAStruct {
    Named { active: bool },
}

union NotAStructEither {
    active: bool,
    bits: u8,
}

// Struct fields generated by a local macro remain under the crate author's control.
macro_rules! local_struct {
    () => {
        struct FromLocalMacro {
            enabled: bool,
        }
    };
}

local_struct!();

// Struct fields generated by an external macro should be ignored.
external_struct!();

// A field-level allow attribute should suppress the warning for that field only.
struct Suppressed {
    #[allow(bool_fields_without_predicate_prefix)]
    active: bool,
}

fn main() {}
