extern crate rustc_ast;
extern crate rustc_hir;
extern crate rustc_lint;
extern crate rustc_middle;
extern crate rustc_span;

use std::collections::{HashMap, HashSet};

use convert_case::{Case, Casing};
#[cfg(feature = "strum")]
use rustc_hir::def::CtorKind;
use rustc_hir::def::{CtorOf, DefKind, Res};
#[cfg(feature = "strum")]
use rustc_hir::def_id::DefId;
use rustc_hir::def_id::LocalDefId;
use rustc_hir::{Arm, Expr, ExprKind, ImplItem, ImplItemKind, Node, Pat, PatExprKind, PatKind};
use rustc_lint::LateContext;
use rustc_middle::ty;
#[cfg(feature = "strum")]
use rustc_middle::ty::util::IntTypeExt;
#[cfg(feature = "strum")]
use rustc_span::symbol::sym;
use rustc_span::{Span, Symbol};

// -----------------------------------------------------------------------------
// BooleanMatchArmCount: Boolean predicate match shape
// -----------------------------------------------------------------------------

/// Exact arm count for a boolean predicate match.
const BOOLEAN_MATCH_ARM_COUNT: usize = 2;

// -----------------------------------------------------------------------------
// AccessorModesPerVariant: Complete variant accessor family size
// -----------------------------------------------------------------------------

/// Owned, shared, and mutable accessors expected for each variant.
const ACCESSOR_MODES_PER_VARIANT: usize = 3;

// -----------------------------------------------------------------------------
// VariantMethods: Generated method contracts and shared evidence
// -----------------------------------------------------------------------------

use crate::config::providers::PredicateProvider;

/// Complete authored predicate family reproducible by `EnumIs`.
pub struct PredicateFamily {
    /// Authored declaration or expression range used as the diagnostic anchor.
    pub(crate) span: Span,
    /// Declaration whose lint level governs this finding.
    pub(crate) owner: rustc_hir::HirId,
    /// Local enum definition that owns the analyzed contract.
    enum_def: LocalDefId,
    /// Whether replacement would change a public API.
    is_public_api: bool,
}

impl PredicateFamily {
    /// Returns every provider directly available to the consumer.
    pub(crate) fn providers(_cx: &LateContext<'_>) -> Vec<PredicateProvider> {
        let mut providers = Vec::new();
        if cfg!(feature = "strum") {
            providers.push(PredicateProvider::StrumEnumIs);
        }
        if cfg!(feature = "derive_more") {
            providers.push(PredicateProvider::DeriveMoreIsVariant);
        }
        providers
    }

    /// Selects the sole provider or the explicitly configured provider.
    pub(crate) fn selected(
        cx: &LateContext<'_>,
        configured: Option<PredicateProvider>,
    ) -> Option<PredicateProvider> {
        let providers = Self::providers(cx);

        // A single enabled provider needs no user-facing disambiguation.
        if providers.len() == 1 {
            return providers.first().copied();
        }
        configured.filter(|provider| providers.contains(provider))
    }

    /// Returns the enum's authored name.
    pub(crate) fn enum_name(&self, cx: &LateContext<'_>) -> Symbol {
        cx.tcx.item_name(self.enum_def.to_def_id())
    }

    /// Returns whether replacing the family changes a public API.
    pub(crate) const fn is_public_api(&self) -> bool {
        self.is_public_api
    }
}

/// Receiver mode generated by `EnumTryAs`.
#[cfg(feature = "strum")]
#[derive(Clone, Copy, Eq, Hash, PartialEq)]
enum AccessorMode {
    /// Returns the payload by value.
    Owned,
    /// Returns a shared reference to the payload.
    Shared,
    /// Returns a mutable reference to the payload.
    Mutable,
}

#[cfg(feature = "strum")]
impl AccessorMode {
    /// Resolves the receiver mode and verifies that it targets the enclosing enum.
    fn receiver_mode(
        cx: &LateContext<'_>,
        definition: LocalDefId,
        enum_def: LocalDefId,
    ) -> Option<Self> {
        let signature = cx
            .tcx
            .fn_sig(definition)
            .instantiate_identity()
            .skip_binder();
        let receiver = signature.inputs().first()?;

        match receiver.kind() {
            ty::Adt(definition, _) if definition.did().as_local() == Some(enum_def) => {
                Some(Self::Owned)
            }
            ty::Ref(_, inner, rustc_hir::Mutability::Not)
                if inner.ty_adt_def()?.did().as_local() == Some(enum_def) =>
            {
                Some(Self::Shared)
            }
            ty::Ref(_, inner, rustc_hir::Mutability::Mut)
                if inner.ty_adt_def()?.did().as_local() == Some(enum_def) =>
            {
                Some(Self::Mutable)
            }
            _ => None,
        }
    }
}

/// Complete authored accessor family reproducible by `EnumTryAs`.
#[cfg(feature = "strum")]
pub struct AccessorFamily {
    /// Authored declaration or expression range used as the diagnostic anchor.
    pub(crate) span: Span,
    /// Declaration whose lint level governs this finding.
    pub(crate) owner: rustc_hir::HirId,
    /// Local enum definition that owns the analyzed contract.
    enum_def: LocalDefId,
    /// Whether replacement would change a public API.
    is_public_api: bool,
}

#[cfg(feature = "strum")]
impl AccessorFamily {
    /// Returns the enum's authored name.
    pub(crate) fn enum_name(&self, cx: &LateContext<'_>) -> Symbol {
        cx.tcx.item_name(self.enum_def.to_def_id())
    }

    /// Returns whether replacing the family changes a public API.
    pub(crate) const fn is_public_api(&self) -> bool {
        self.is_public_api
    }
}

/// Authored Strum metadata inspection for enum variants.
pub struct VariantMetadata;

impl VariantMetadata {
    /// Returns whether one variant is excluded by canonical `#[strum(disabled)]` metadata.
    pub fn is_strum_disabled(cx: &LateContext<'_>, hir_id: rustc_hir::HirId) -> bool {
        let span = cx.tcx.hir_span(hir_id);
        let source_map = cx.tcx.sess.source_map();
        let location = source_map.lookup_char_pos(span.lo());

        // Attribute scanning requires the compiler to retain this file's source text.
        let Some(file_source) = location.file.src.as_deref() else {
            return false;
        };

        // A span outside its source file cannot identify the preceding attributes.
        let Some(raw_offset) = span.lo().0.checked_sub(location.file.start_pos.0) else {
            return false;
        };

        // The byte offset must fit the source slice before it can be indexed.
        let Ok(offset) = usize::try_from(raw_offset) else {
            return false;
        };
        let bytes = file_source.as_bytes();
        let mut start = offset;
        loop {
            while start > 0 && bytes[start - 1].is_ascii_whitespace() {
                start -= 1;
            }
            if start == 0 || bytes[start - 1] != b']' {
                break;
            }
            let mut cursor = start - 1;
            let mut depth = 1_u32;
            while cursor > 0 && depth > 0 {
                cursor -= 1;
                match bytes[cursor] {
                    b']' => depth += 1,
                    b'[' => depth -= 1,
                    _ => {}
                }
            }
            if depth != 0 || cursor == 0 || bytes[cursor - 1] != b'#' {
                break;
            }
            start = cursor - 1;
        }

        file_source[start..offset].split("#[").any(|attribute| {
            attribute.trim_start().starts_with("strum")
                && attribute
                    .split(|character: char| !(character.is_alphanumeric() || character == '_'))
                    .any(|component| component == "disabled")
        })
    }
}

/// Resolves a positive integer literal pattern.
#[cfg(feature = "strum")]
fn integer_pattern(pattern: &Pat<'_>) -> Option<u128> {
    // Only expression patterns can encode a literal discriminant.
    let PatKind::Expr(expression) = pattern.kind else {
        return None;
    };

    // Negative and non-literal patterns do not represent supported discriminants.
    let PatExprKind::Lit {
        lit: literal,
        negated: false,
    } = expression.kind
    else {
        return None;
    };

    // Repr conversion matching requires an integer literal specifically.
    let rustc_ast::LitKind::Int(value, _) = literal.node else {
        return None;
    };
    Some(value.get())
}

/// Resolves a path or constructor resolution to its local variant definition.
fn variant_from_res(cx: &LateContext<'_>, resolution: Res) -> Option<LocalDefId> {
    match resolution {
        Res::Def(DefKind::Variant, variant) => variant.as_local(),
        Res::Def(DefKind::Ctor(CtorOf::Variant, _), constructor) => {
            cx.tcx.opt_local_parent(constructor.as_local()?)
        }
        _ => None,
    }
}

/// Resolves a variant pattern whose payload is entirely ignored.
fn ignored_variant_pattern(cx: &LateContext<'_>, pattern: &Pat<'_>) -> Option<LocalDefId> {
    let resolution = match pattern.kind {
        PatKind::Expr(expression) => {
            // A payload-free variant must be written as a direct path.
            let PatExprKind::Path(path) = expression.kind else {
                return None;
            };
            cx.qpath_res(&path, expression.hir_id)
        }
        PatKind::TupleStruct(path, fields, _)
            if fields
                .iter()
                .all(|field| matches!(field.kind, PatKind::Wild)) =>
        {
            cx.qpath_res(&path, pattern.hir_id)
        }
        PatKind::Struct(path, fields, _)
            if fields
                .iter()
                .all(|field| matches!(field.pat.kind, PatKind::Wild)) =>
        {
            cx.qpath_res(&path, pattern.hir_id)
        }

        // Any other pattern can observe or bind payload data.
        _ => return None,
    };

    variant_from_res(cx, resolution)
}

/// Resolves one plain binding pattern.
const fn binding_id(pattern: &Pat<'_>) -> Option<rustc_hir::HirId> {
    // Generated accessors require an unmodified binding for each payload field.
    let PatKind::Binding(_, binding, _, None) = pattern.kind else {
        return None;
    };
    Some(binding)
}

/// Tuple-variant identity and its ordered field bindings.
#[cfg(feature = "strum")]
struct BoundTupleVariant {
    /// Matched local enum variant.
    variant: LocalDefId,
    /// Ordered bindings for the variant payload.
    bindings: Vec<rustc_hir::HirId>,
}

#[cfg(feature = "strum")]
impl BoundTupleVariant {
    /// Resolves a tuple-variant pattern and its ordered field bindings.
    fn analyze(cx: &LateContext<'_>, pattern: &Pat<'_>) -> Option<Self> {
        // Only tuple-variant patterns can establish ordered payload bindings.
        let PatKind::TupleStruct(path, fields, rest) = pattern.kind else {
            return None;
        };

        // A rest pattern omits fields, so it cannot prove an exact accessor.
        if rest.as_opt_usize().is_some() {
            return None;
        }

        let bindings = fields
            .iter()
            .map(|field| binding_id(field))
            .collect::<Option<Vec<_>>>()?;

        Some(Self {
            variant: variant_from_res(cx, cx.qpath_res(&path, pattern.hir_id))?,
            bindings,
        })
    }
}

/// Returns whether a constructor is the named variant of standard `Option`.
#[cfg(feature = "strum")]
fn is_option_variant(cx: &LateContext<'_>, constructor: DefId, name: &str) -> bool {
    let variant = cx.tcx.parent(constructor);
    cx.tcx.item_name(variant).as_str() == name
        && cx
            .tcx
            .is_diagnostic_item(sym::Option, cx.tcx.parent(variant))
}

/// Returns the payload of an exact standard `Option` return type.
#[cfg(feature = "strum")]
fn option_output<'tcx>(cx: &LateContext<'tcx>, definition: LocalDefId) -> Option<ty::Ty<'tcx>> {
    let output = cx
        .tcx
        .fn_sig(definition)
        .instantiate_identity()
        .skip_binder()
        .output();

    // Accessor recognition is meaningful only for an exact `Option` result.
    let ty::Adt(option, arguments) = output.kind() else {
        return None;
    };
    cx.tcx
        .is_diagnostic_item(sym::Option, option.did())
        .then(|| arguments.type_at(0))
}

/// Verifies the shared receiver contract generated by `EnumIs`.
fn has_shared_receiver(cx: &LateContext<'_>, definition: LocalDefId, enum_def: LocalDefId) -> bool {
    let signature = cx
        .tcx
        .fn_sig(definition)
        .instantiate_identity()
        .skip_binder();

    // Predicate methods must have a receiver to be generated from the enum.
    let Some(receiver) = signature.inputs().first() else {
        return false;
    };
    matches!(
        receiver.kind(),
        ty::Ref(_, inner, rustc_hir::Mutability::Not)
            if inner.ty_adt_def().is_some_and(|definition| definition.did().as_local() == Some(enum_def))
    ) && signature.output().is_bool()
}

/// Finds the local enum targeted by an inherent implementation item.
fn enclosing_inherent_enum(cx: &LateContext<'_>, hir_id: rustc_hir::HirId) -> Option<LocalDefId> {
    cx.tcx.hir_parent_iter(hir_id).find_map(|(_, node)| {
        // Only item ancestors can contain an inherent implementation.
        let Node::Item(item) = node else {
            return None;
        };

        // The candidate must live in an implementation item.
        let rustc_hir::ItemKind::Impl(implementation) = item.kind else {
            return None;
        };

        // Trait implementations do not establish inherent generated methods.
        if implementation.of_trait.is_some() {
            return None;
        }
        cx.tcx
            .type_of(item.owner_id)
            .instantiate_identity()
            .ty_adt_def()?
            .did()
            .as_local()
    })
}

/// Returns the enum owning one local variant.
fn owning_enum(cx: &LateContext<'_>, variant: LocalDefId) -> Option<LocalDefId> {
    cx.tcx.opt_local_parent(variant)
}

/// Rejects enums whose variant attributes may disable or rename generated methods.
fn has_enum_strum_variant_attributes(cx: &LateContext<'_>, enum_def: LocalDefId) -> bool {
    // Unknown HIR structure may hide attributes that alter generated coverage.
    let Node::Item(item) = cx.tcx.hir_node_by_def_id(enum_def) else {
        return true;
    };

    // Only enum definitions expose the variant metadata being checked.
    let rustc_hir::ItemKind::Enum(_, _, definition) = item.kind else {
        return true;
    };
    let strum = Symbol::intern("strum");
    definition.variants.iter().any(|variant| {
        cx.tcx
            .hir_attrs(variant.hir_id)
            .iter()
            .any(|attribute| attribute.has_name(strum))
    })
}

/// Returns whether Strum excludes any variant from generated enum APIs.
#[cfg(feature = "strum")]
fn has_enum_strum_disabled_variant(cx: &LateContext<'_>, enum_def: LocalDefId) -> bool {
    // Unknown HIR structure may hide disabled variants.
    let Node::Item(item) = cx.tcx.hir_node_by_def_id(enum_def) else {
        return true;
    };

    // Only enum definitions expose the disabled-variant metadata.
    let rustc_hir::ItemKind::Enum(_, _, definition) = item.kind else {
        return true;
    };
    definition
        .variants
        .iter()
        .any(|variant| VariantMetadata::is_strum_disabled(cx, variant.hir_id))
}

/// Returns every variant when Strum attributes cannot change generated coverage.
fn eligible_variants(
    cx: &LateContext<'_>,
    enum_def: LocalDefId,
    provider: Option<PredicateProvider>,
) -> Option<Vec<LocalDefId>> {
    // Strum metadata can change coverage unless a concrete provider was selected.
    if provider.is_none() && has_enum_strum_variant_attributes(cx, enum_def) {
        return None;
    }

    // The candidate must resolve to a local enum item.
    let Node::Item(item) = cx.tcx.hir_node_by_def_id(enum_def) else {
        return None;
    };

    // Variant enumeration requires the item to remain an enum.
    let rustc_hir::ItemKind::Enum(_, _, definition) = item.kind else {
        return None;
    };
    Some(
        definition
            .variants
            .iter()
            .filter(|variant| {
                provider != Some(PredicateProvider::StrumEnumIs)
                    || !VariantMetadata::is_strum_disabled(cx, variant.hir_id)
            })
            .map(|variant| variant.def_id)
            .collect(),
    )
}

/// Returns every tuple variant when Strum attributes cannot change generated coverage.
#[cfg(feature = "strum")]
fn eligible_tuple_variants(cx: &LateContext<'_>, enum_def: LocalDefId) -> Option<Vec<LocalDefId>> {
    let variants = eligible_variants(cx, enum_def, Some(PredicateProvider::StrumEnumIs))?;
    let definition = cx.tcx.adt_def(enum_def.to_def_id());

    Some(
        variants
            .into_iter()
            .filter(|variant| {
                definition
                    .variants()
                    .iter()
                    .find(|candidate| candidate.def_id.as_local() == Some(*variant))
                    .is_some_and(|candidate| {
                        !candidate.fields.is_empty() && candidate.ctor_kind() == Some(CtorKind::Fn)
                    })
            })
            .collect(),
    )
}

/// Removes blocks and compiler drop-temporary wrappers without changing semantics.
const fn peel_transparent<'hir>(mut expression: &'hir Expr<'hir>) -> &'hir Expr<'hir> {
    loop {
        expression = match expression.kind {
            ExprKind::Block(block, None) if block.stmts.is_empty() => {
                // An empty block without a tail expression cannot be peeled further.
                let Some(inner) = block.expr else {
                    return expression;
                };
                inner
            }
            ExprKind::DropTemps(inner) => inner,

            // Any other expression wrapper is semantically significant.
            _ => return expression,
        };
    }
}

/// Resolves a literal boolean after transparent blocks.
const fn is_bool_literal(expression: &Expr<'_>) -> Option<bool> {
    // Only literal expressions can prove a boolean match arm's result.
    let ExprKind::Lit(literal) = peel_transparent(expression).kind else {
        return None;
    };

    // Non-boolean literals do not identify a positive or negative arm.
    let rustc_ast::LitKind::Bool(value) = literal.node else {
        return None;
    };
    Some(value)
}

/// Positive and negative branches of a complete boolean match.
struct BoolArms<'hir> {
    /// Arm returning `true`.
    positive: &'hir Arm<'hir>,
    /// Arm returning `false`.
    negative: &'hir Arm<'hir>,
}

impl<'hir> BoolArms<'hir> {
    /// Finds the true and false arms of a boolean match.
    fn analyze(arms: &'hir [Arm<'hir>]) -> Option<Self> {
        Some(Self {
            positive: arms
                .iter()
                .find(|arm| is_bool_literal(arm.body) == Some(true))?,
            negative: arms
                .iter()
                .find(|arm| is_bool_literal(arm.body) == Some(false))?,
        })
    }
}

/// Resolves a direct unit-variant expression.
#[cfg(feature = "strum")]
fn unit_variant_expression(cx: &LateContext<'_>, expression: &Expr<'_>) -> Option<LocalDefId> {
    // A unit variant result must be a direct constructor path.
    let ExprKind::Path(path) = peel_transparent(expression).kind else {
        return None;
    };
    variant_from_res(cx, cx.qpath_res(&path, expression.hir_id))
}

/// Returns whether an expression is a direct path to a local binding.
fn is_local_path(cx: &LateContext<'_>, expression: &Expr<'_>, binding: rustc_hir::HirId) -> bool {
    let expression = peel_transparent(expression);

    // Only direct paths can be compared with the captured binding.
    let ExprKind::Path(path) = expression.kind else {
        return false;
    };
    matches!(cx.qpath_res(&path, expression.hir_id), Res::Local(found) if found == binding)
}

/// Checks that a `Some` payload returns every pattern binding in order.
#[cfg(feature = "strum")]
fn is_returning_bindings(
    cx: &LateContext<'_>,
    expression: &Expr<'_>,
    bindings: &[rustc_hir::HirId],
) -> bool {
    // A single binding is returned directly rather than wrapped in a tuple.
    if bindings.len() == 1 {
        return is_local_path(cx, expression, bindings[0]);
    }

    // Multiple bindings must be returned in their original tuple shape.
    let ExprKind::Tup(elements) = peel_transparent(expression).kind else {
        return false;
    };

    elements.len() == bindings.len()
        && elements
            .iter()
            .zip(bindings)
            .all(|(element, binding)| is_local_path(cx, element, *binding))
}

/// Variant identity and authored span recovered from a method body.
struct VariantMethodMatch {
    /// Variant handled by the method.
    variant: LocalDefId,
    /// Authored match expression.
    span: Span,
}

impl VariantMethodMatch {
    /// Exact arm count for a complete `Option` accessor match.
    #[cfg(feature = "strum")]
    const OPTION_MATCH_ARM_COUNT: usize = 2;

    /// Resolves an exact two-arm variant predicate.
    fn predicate(
        cx: &LateContext<'_>,
        expression: &Expr<'_>,
        receiver: rustc_hir::HirId,
    ) -> Option<Self> {
        let expression = peel_transparent(expression);

        // Predicate recognition starts with an explicit match expression.
        let ExprKind::Match(scrutinee, arms, _) = expression.kind else {
            return None;
        };

        // The match must cover only the receiver with exactly two outcomes.
        if !is_local_path(cx, scrutinee, receiver) || arms.len() != BOOLEAN_MATCH_ARM_COUNT {
            return None;
        }

        let BoolArms { positive, negative } = BoolArms::analyze(arms)?;

        // Guards or a non-wildcard fallback prevent a complete generated predicate.
        if positive.guard.is_some()
            || negative.guard.is_some()
            || !matches!(negative.pat.kind, PatKind::Wild)
        {
            return None;
        }

        let variant = ignored_variant_pattern(cx, positive.pat)?;
        Some(Self {
            variant,
            span: expression.span.source_callsite(),
        })
    }

    /// Resolves an exact two-arm payload extraction match.
    #[cfg(feature = "strum")]
    fn accessor(
        cx: &LateContext<'_>,
        expression: &Expr<'_>,
        receiver: rustc_hir::HirId,
    ) -> Option<Self> {
        let expression = peel_transparent(expression);

        // Accessor recognition starts with an explicit match expression.
        let ExprKind::Match(scrutinee, arms, _) = expression.kind else {
            return None;
        };

        // The match must cover only the receiver with `Some` and fallback arms.
        if !is_local_path(cx, scrutinee, receiver) || arms.len() != Self::OPTION_MATCH_ARM_COUNT {
            return None;
        }

        let success = arms
            .iter()
            .find(|arm| option_some(cx, arm.body).is_some())?;
        let failure = arms.iter().find(|arm| is_option_none(cx, arm.body))?;

        // Guards or a non-wildcard fallback prevent a complete generated accessor.
        if success.guard.is_some()
            || failure.guard.is_some()
            || !matches!(failure.pat.kind, PatKind::Wild)
        {
            return None;
        }
        let BoundTupleVariant { variant, bindings } = BoundTupleVariant::analyze(cx, success.pat)?;
        let returned = option_some(cx, success.body)?;

        // The success arm must return the original payload without transformation.
        if !is_returning_bindings(cx, returned, &bindings) {
            return None;
        }
        Some(Self {
            variant,
            span: expression.span.source_callsite(),
        })
    }
}

// -----------------------------------------------------------------------------
// Predicate: Crate-wide predicate-family assembly
// -----------------------------------------------------------------------------

/// One exact `is_variant`-style inherent method.
struct PredicateMethod {
    /// Authored declaration or expression range used as the diagnostic anchor.
    span: Span,
    /// Declaration whose lint level governs this finding.
    owner: rustc_hir::HirId,
    /// Local enum definition that owns the analyzed contract.
    enum_def: LocalDefId,
    /// Variant identity involved in the finding.
    variant: LocalDefId,
    /// Whether replacement would change a public API.
    is_public_api: bool,
}

impl PredicateMethod {
    /// Resolves one shared-receiver, exact single-variant boolean match.
    fn from_impl_item(cx: &LateContext<'_>, item: &ImplItem<'_>) -> Option<Self> {
        // Generated methods cannot be identified reliably inside macro expansions.
        if item.span.from_expansion() {
            return None;
        }

        // Only function implementation items can supply a predicate body.
        let ImplItemKind::Fn(signature, body_id) = item.kind else {
            return None;
        };

        // Generated predicates must retain Strum's public, simple method contract.
        if signature.decl.inputs.len() != 1
            || signature.header.is_unsafe()
            || signature.header.is_async()
            || !cx
                .tcx
                .generics_of(item.owner_id.def_id)
                .own_params
                .is_empty()
            || !cx.tcx.visibility(item.owner_id.def_id).is_public()
            || !cx.tcx.hir_attrs(item.hir_id()).is_empty()
        {
            return None;
        }

        // Resolve the exact enum variant and receiver field returned by the accessor.
        let enum_def = enclosing_inherent_enum(cx, item.hir_id())?;

        // The method must borrow precisely the enum it is associated with.
        if !has_shared_receiver(cx, item.owner_id.def_id, enum_def) {
            return None;
        }

        let body = cx.tcx.hir_body(body_id);
        let receiver = binding_id(body.params.first()?.pat)?;
        let VariantMethodMatch { variant, span } =
            VariantMethodMatch::predicate(cx, body.value, receiver)?;

        // The matched variant must belong to the enclosing enum.
        if owning_enum(cx, variant) != Some(enum_def) {
            return None;
        }

        let expected_name = format!(
            "is_{}",
            cx.tcx
                .item_name(variant.to_def_id())
                .as_str()
                .to_case(Case::Snake)
        );

        // The public method name must match the generated predicate naming scheme.
        if item.ident.name.as_str() != expected_name {
            return None;
        }

        Some(Self {
            span,
            owner: item.hir_id(),
            enum_def,
            variant,
            is_public_api: cx.tcx.visibility(item.owner_id.def_id).is_public(),
        })
    }
}

/// Accumulates predicate methods until a complete enum family can be proven.
#[derive(Default)]
pub struct PredicateFamilyAnalyzer {
    /// Methods whose bodies establish the finding.
    methods: HashMap<LocalDefId, Vec<PredicateMethod>>,
}

impl PredicateFamilyAnalyzer {
    /// Records one exact authored variant predicate when eligible.
    pub(crate) fn check_impl_item(&mut self, cx: &LateContext<'_>, item: &ImplItem<'_>) {
        // Only complete predicate methods contribute evidence to a family.
        let Some(method) = PredicateMethod::from_impl_item(cx, item) else {
            return;
        };
        self.methods
            .entry(method.enum_def)
            .or_default()
            .push(method);
    }

    /// Returns only families covering every enabled enum variant exactly once.
    pub(crate) fn complete_families(
        &self,
        cx: &LateContext<'_>,
        provider: Option<PredicateProvider>,
    ) -> Vec<PredicateFamily> {
        let mut families = self
            .methods
            .iter()
            .filter_map(|(&enum_def, methods)| {
                let expected = eligible_variants(cx, enum_def, provider)?;
                let found = methods
                    .iter()
                    .map(|method| method.variant)
                    .collect::<HashSet<_>>();

                // A replacement is sound only when every eligible variant is represented once.
                if methods.len() != expected.len()
                    || found.len() != expected.len()
                    || !expected.iter().all(|variant| found.contains(variant))
                {
                    return None;
                }
                let first = methods.first()?;
                Some(PredicateFamily {
                    span: first.span,
                    owner: first.owner,
                    enum_def,
                    is_public_api: methods.iter().any(|method| method.is_public_api),
                })
            })
            .collect::<Vec<_>>();
        families.sort_by_key(|family| family.span.lo());
        families
    }
}

// -----------------------------------------------------------------------------
// ReprConversionCandidate: Exact integer-to-variant conversion
// -----------------------------------------------------------------------------

/// Returns the payload expression inside standard `Option::Some`.
#[cfg(feature = "strum")]
fn option_some<'hir>(
    cx: &LateContext<'_>,
    expression: &'hir Expr<'hir>,
) -> Option<&'hir Expr<'hir>> {
    let expression = peel_transparent(expression);

    // `Some` recognition requires a one-argument constructor call.
    let ExprKind::Call(callee, [value]) = expression.kind else {
        return None;
    };

    // The constructor itself must be named by a direct path.
    let ExprKind::Path(path) = peel_transparent(callee).kind else {
        return None;
    };

    // Only a resolved variant constructor can be standard `Option::Some`.
    let Res::Def(DefKind::Ctor(CtorOf::Variant, _), constructor) =
        cx.qpath_res(&path, callee.hir_id)
    else {
        return None;
    };
    is_option_variant(cx, constructor, "Some").then_some(value)
}

/// Returns whether an expression is standard `Option::None`.
#[cfg(feature = "strum")]
fn is_option_none(cx: &LateContext<'_>, expression: &Expr<'_>) -> bool {
    let expression = peel_transparent(expression);

    // `None` recognition requires a direct constructor path.
    let ExprKind::Path(path) = expression.kind else {
        return false;
    };
    matches!(cx.qpath_res(&path, expression.hir_id), Res::Def(DefKind::Ctor(CtorOf::Variant, _), constructor) if is_option_variant(cx, constructor, "None"))
}

/// Resolves an exhaustive positive integer discriminant match.
#[cfg(feature = "strum")]
fn repr_match(
    cx: &LateContext<'_>,
    expression: &Expr<'_>,
    input: rustc_hir::HirId,
    enum_def: LocalDefId,
) -> Option<Span> {
    let expression = peel_transparent(expression);

    // Repr conversion recognition requires a literal match expression.
    let ExprKind::Match(scrutinee, arms, _) = expression.kind else {
        return None;
    };

    // The match must dispatch directly on the conversion input.
    if !is_local_path(cx, scrutinee, input) {
        return None;
    }

    let mut observed = HashMap::new();
    let mut has_fallback = false;

    for arm in arms {
        // Guarded arms cannot establish an exhaustive discriminant mapping.
        if arm.guard.is_some() {
            return None;
        }
        if matches!(arm.pat.kind, PatKind::Wild) && is_option_none(cx, arm.body) {
            has_fallback = true;
            continue;
        }
        let value = integer_pattern(arm.pat)?;
        let variant_expression = option_some(cx, arm.body)?;
        let variant = unit_variant_expression(cx, variant_expression)?;

        // Every literal must select one distinct variant of the candidate enum.
        if owning_enum(cx, variant) != Some(enum_def) || observed.insert(variant, value).is_some() {
            return None;
        }
    }

    // A generated conversion needs an uncovered-value fallback and no disabled variants.
    if !has_fallback || has_enum_strum_disabled_variant(cx, enum_def) {
        return None;
    }
    let definition = cx.tcx.adt_def(enum_def.to_def_id());

    // Every enum variant must be unit-like and mapped to its actual discriminant.
    if definition
        .variants()
        .iter()
        .any(|variant| !variant.fields.is_empty())
        || observed.len() != definition.variants().len()
        || definition
            .variants()
            .iter_enumerated()
            .any(|(index, variant)| {
                variant.def_id.as_local().is_none_or(|variant_def| {
                    observed.get(&variant_def).copied()
                        != Some(definition.discriminant_for_variant(cx.tcx, index).val)
                })
            })
    {
        return None;
    }

    for (index, discriminant) in definition.discriminants(cx.tcx) {
        let variant = definition.variant(index).def_id.as_local()?;

        // The observed literal must agree with the compiler's discriminant value.
        if observed.get(&variant).copied() != Some(discriminant.val) {
            return None;
        }
    }
    Some(expression.span.source_callsite())
}

/// One exact inherent integer-to-unit-variant conversion reproducible by `FromRepr`.
#[cfg(feature = "strum")]
pub struct ReprConversionCandidate {
    /// Authored declaration or expression range used as the diagnostic anchor.
    pub(crate) span: Span,
    /// Declaration whose lint level governs this finding.
    pub(crate) owner: rustc_hir::HirId,
    /// Local enum definition that owns the analyzed contract.
    enum_def: LocalDefId,
    /// Whether replacement would change a public API.
    is_public_api: bool,
}

#[cfg(feature = "strum")]
impl ReprConversionCandidate {
    /// Resolves an exhaustive literal-to-variant `from_repr` implementation.
    pub(crate) fn from_impl_item(cx: &LateContext<'_>, item: &ImplItem<'_>) -> Option<Self> {
        // Generated or differently named methods are not authored `from_repr` candidates.
        if item.span.from_expansion() || item.ident.name.as_str() != "from_repr" {
            return None;
        }

        // Only function implementation items can implement the conversion.
        let ImplItemKind::Fn(signature, body_id) = item.kind else {
            return None;
        };

        // `FromRepr` accepts exactly one integer input.
        if signature.decl.inputs.len() != 1 {
            return None;
        }
        let enum_def = enclosing_inherent_enum(cx, item.hir_id())?;
        let definition = cx.tcx.adt_def(enum_def.to_def_id());
        let repr = definition.repr().int?;
        let signature = cx
            .tcx
            .fn_sig(item.owner_id.def_id)
            .instantiate_identity()
            .skip_binder();

        // The input type must match the enum's declared integer representation.
        if signature.inputs()[0] != repr.to_ty(cx.tcx) {
            return None;
        }
        let output = option_output(cx, item.owner_id.def_id)?;

        // The `Option` payload must be the enclosing enum itself.
        if output.ty_adt_def()?.did().as_local() != Some(enum_def) {
            return None;
        }
        let body = cx.tcx.hir_body(body_id);
        let input = binding_id(body.params.first()?.pat)?;
        let span = repr_match(cx, body.value, input, enum_def)?;

        Some(Self {
            span,
            owner: item.hir_id(),
            enum_def,
            is_public_api: cx.tcx.visibility(item.owner_id.def_id).is_public(),
        })
    }

    /// Returns the enum's authored name.
    pub(crate) fn enum_name(&self, cx: &LateContext<'_>) -> Symbol {
        cx.tcx.item_name(self.enum_def.to_def_id())
    }

    /// Returns whether replacing the method changes a public API.
    pub(crate) const fn is_public_api(&self) -> bool {
        self.is_public_api
    }
}

// -----------------------------------------------------------------------------
// Accessor: Crate-wide accessor-family assembly
// -----------------------------------------------------------------------------

/// One exact owned, shared, or mutable tuple-variant accessor.
#[cfg(feature = "strum")]
struct AccessorMethod {
    /// Authored declaration or expression range used as the diagnostic anchor.
    span: Span,
    /// Declaration whose lint level governs this finding.
    owner: rustc_hir::HirId,
    /// Local enum definition that owns the analyzed contract.
    enum_def: LocalDefId,
    /// Variant identity involved in the finding.
    variant: LocalDefId,
    /// Owned or borrowed receiver form implemented by this accessor.
    mode: AccessorMode,
    /// Whether replacement would change a public API.
    is_public_api: bool,
}

#[cfg(feature = "strum")]
impl AccessorMethod {
    /// Resolves one `Option` accessor that returns bound fields without transformation.
    fn from_impl_item(cx: &LateContext<'_>, item: &ImplItem<'_>) -> Option<Self> {
        // Generated methods cannot be identified reliably inside macro expansions.
        if item.span.from_expansion() {
            return None;
        }

        // Only function implementation items can supply an accessor body.
        let ImplItemKind::Fn(signature, body_id) = item.kind else {
            return None;
        };

        // Generated accessors must retain Strum's public, simple method contract.
        if signature.decl.inputs.len() != 1
            || signature.header.is_unsafe()
            || signature.header.is_async()
            || !cx
                .tcx
                .generics_of(item.owner_id.def_id)
                .own_params
                .is_empty()
            || !cx.tcx.visibility(item.owner_id.def_id).is_public()
            || cx
                .tcx
                .hir_attrs(item.hir_id())
                .iter()
                .any(|attribute| attribute.doc_str().is_some())
        {
            return None;
        }

        // Resolve the enum receiver and verify that the accessor returns an Option.
        let enum_def = enclosing_inherent_enum(cx, item.hir_id())?;
        let mode = AccessorMode::receiver_mode(cx, item.owner_id.def_id, enum_def)?;
        option_output(cx, item.owner_id.def_id)?;
        let body = cx.tcx.hir_body(body_id);

        let receiver = binding_id(body.params.first()?.pat)?;
        let VariantMethodMatch { variant, span } =
            VariantMethodMatch::accessor(cx, body.value, receiver)?;

        // The matched variant must belong to the enclosing enum.
        if owning_enum(cx, variant) != Some(enum_def) {
            return None;
        }

        let suffix = match mode {
            AccessorMode::Owned => "",
            AccessorMode::Shared => "_ref",
            AccessorMode::Mutable => "_mut",
        };

        let expected_name = format!(
            "try_as_{}{}",
            cx.tcx
                .item_name(variant.to_def_id())
                .as_str()
                .to_case(Case::Snake),
            suffix
        );

        // The method name must match the generated accessor naming scheme.
        if item.ident.name.as_str() != expected_name {
            return None;
        }

        Some(Self {
            span,
            owner: item.hir_id(),
            enum_def,
            variant,
            mode,
            is_public_api: cx.tcx.visibility(item.owner_id.def_id).is_public(),
        })
    }
}

/// Accumulates exact payload accessors until every generated method is represented.
#[cfg(feature = "strum")]
#[derive(Default)]
pub struct AccessorFamilyAnalyzer {
    /// Methods whose bodies establish the finding.
    methods: HashMap<LocalDefId, Vec<AccessorMethod>>,
}

#[cfg(feature = "strum")]
impl AccessorFamilyAnalyzer {
    /// Records one exact authored tuple-variant accessor when eligible.
    pub(crate) fn check_impl_item(&mut self, cx: &LateContext<'_>, item: &ImplItem<'_>) {
        // Only complete accessors contribute evidence to a family.
        let Some(method) = AccessorMethod::from_impl_item(cx, item) else {
            return;
        };
        self.methods
            .entry(method.enum_def)
            .or_default()
            .push(method);
    }

    /// Returns only families matching all three generated modes for every tuple variant.
    pub(crate) fn complete_families(&self, cx: &LateContext<'_>) -> Vec<AccessorFamily> {
        let mut families = self
            .methods
            .iter()
            .filter_map(|(&enum_def, methods)| {
                let variants = eligible_tuple_variants(cx, enum_def)?;
                let expected = variants.len().checked_mul(ACCESSOR_MODES_PER_VARIANT)?;
                let found = methods
                    .iter()
                    .map(|method| (method.variant, method.mode))
                    .collect::<HashSet<_>>();

                // A replacement is sound only when every variant has every accessor mode.
                if methods.len() != expected
                    || found.len() != expected
                    || !variants.iter().all(|variant| {
                        [
                            AccessorMode::Owned,
                            AccessorMode::Shared,
                            AccessorMode::Mutable,
                        ]
                        .into_iter()
                        .all(|mode| found.contains(&(*variant, mode)))
                    })
                {
                    return None;
                }
                let first = methods.first()?;
                Some(AccessorFamily {
                    span: first.span,
                    owner: first.owner,
                    enum_def,
                    is_public_api: methods.iter().any(|method| method.is_public_api),
                })
            })
            .collect::<Vec<_>>();
        families.sort_by_key(|family| family.span.lo());
        families
    }
}
