extern crate rustc_hir;
extern crate rustc_lint;
extern crate rustc_span;

use std::collections::{HashMap, HashSet};

use heck::{
    ToKebabCase, ToLowerCamelCase, ToShoutyKebabCase, ToShoutySnakeCase, ToSnakeCase, ToTitleCase,
    ToTrainCase, ToUpperCamelCase,
};
use rustc_hir::def::DefKind;
use rustc_hir::def_id::LocalDefId;
use rustc_hir::{Expr, ExprKind, Item, ItemKind, QPath};
use rustc_lint::LateContext;
use rustc_span::symbol::sym;
use rustc_span::{Span, Symbol};
use syn::meta::ParseNestedMeta;
use syn::{LitBool, LitStr, Token};

use super::authored_contracts::StringTableCandidate;

/// Identifier and nominal type name compared by component boundaries.
struct IdentifierTypeNames<'name> {
    /// Authored identifier being inspected.
    identifier: &'name str,
    /// Type name expected as a complete component sequence.
    type_name: &'name str,
}

/// Returns whether an identifier contains a type name as complete, contiguous name components.
impl IdentifierTypeNames<'_> {
    /// Returns whether the identifier contains the type name as complete components.
    fn identifier_mentions_type(&self) -> bool {
        let identifier = self.identifier.trim_start_matches("r#").to_snake_case();
        let type_name = self.type_name.trim_start_matches("r#").to_snake_case();
        let identifier_components = identifier.split('_').collect::<Vec<_>>();
        let type_components = type_name.split('_').collect::<Vec<_>>();

        identifier_components
            .windows(type_components.len())
            .any(|window| window == type_components)
    }
}

// -----------------------------------------------------------------------------
// Strum: Derive and property vocabulary
// -----------------------------------------------------------------------------

/// One named value carried by a Strum `props` attribute.
#[derive(Clone)]
struct StrumProperty {
    /// Property name.
    name: String,
    /// Property value.
    _value: String,
}

/// Strum derive macros relevant to the framework-aware lint layer.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum StrumDerive {
    /// Borrowed string views generated by `AsRefStr`.
    AsRefStr,
    /// Formatting generated by `Display`.
    Display,
    /// Variant cardinality generated by `EnumCount`.
    EnumCount,
    /// Companion discriminant types generated by `EnumDiscriminants`.
    EnumDiscriminants,
    /// Variant iteration generated by `EnumIter`.
    EnumIter,
    /// Runtime messages generated by `EnumMessage`.
    EnumMessage,
    /// Static metadata generated by `EnumProperty`.
    EnumProperty,
    /// String parsing generated by `EnumString`.
    EnumString,
    /// Discriminant conversion generated by `FromRepr`.
    FromRepr,
    /// Owned-to-static-string conversion generated by `IntoStaticStr`.
    IntoStaticStr,
    /// Ordered variant arrays generated by `VariantArray`.
    VariantArray,
    /// Variant spelling tables generated by `VariantNames`.
    VariantNames,
}

impl StrumDerive {
    /// Resolves the Strum behavior generated by a derive macro name.
    fn from_macro_name(name: &str) -> Option<Self> {
        match name {
            "AsRefStr" => Some(Self::AsRefStr),
            "Display" => Some(Self::Display),
            "EnumCount" => Some(Self::EnumCount),
            "EnumDiscriminants" => Some(Self::EnumDiscriminants),
            "EnumIter" => Some(Self::EnumIter),
            "EnumMessage" => Some(Self::EnumMessage),
            "EnumProperty" => Some(Self::EnumProperty),
            "EnumString" => Some(Self::EnumString),
            "FromRepr" => Some(Self::FromRepr),
            "IntoStaticStr" => Some(Self::IntoStaticStr),
            "VariantArray" => Some(Self::VariantArray),
            "VariantNames" | "EnumVariantNames" => Some(Self::VariantNames),
            _ => None,
        }
    }
}

// -----------------------------------------------------------------------------
// EnumContract: Effective generated behavior for one enum
// -----------------------------------------------------------------------------

/// Effective Strum naming and behavior for one authored enum.
#[derive(Clone)]
pub struct EnumContract {
    /// Compiler identity used to correlate authored and generated enum evidence.
    pub(crate) def_id: LocalDefId,
    /// Declaration whose lint level governs this finding.
    pub(crate) owner: rustc_hir::HirId,
    /// Authored declaration or expression range used as the diagnostic anchor.
    pub(crate) span: Span,
    /// Full authored enum range, including the Strum attributes that define its policy.
    source_span: Span,
    /// Authored enum or variant name involved in the Strum contract.
    pub(crate) name: Symbol,
    /// Whether the declaration is visible outside its defining module.
    pub(crate) is_public: bool,
    /// Variants participating in the analyzed contract.
    pub(crate) variants: Vec<VariantContract>,
    /// Derive macros that establish the generated behavior.
    derives: HashSet<StrumDerive>,
    /// Generated discriminant enum associated with this source enum, if present.
    generated_discriminant: Option<LocalDefId>,
    /// Whether the generated discriminant participates in an external Serde schema.
    pub(crate) is_discriminant_external_schema: bool,
}

impl EnumContract {
    /// Builds the effective Strum contract for one authored enum declaration.
    fn from_item(cx: &LateContext<'_>, item: &Item<'_>) -> Option<Self> {
        // Non-enum items have no variant-level Strum contract.
        let ItemKind::Enum(_, _, definition) = item.kind else {
            return None;
        };
        let source_attributes = SourceAttributes::from_item(cx, item);
        let type_attributes = source_attributes
            .as_ref()
            .map_or_else(TypeAttributes::default, |source| source.ty.clone());

        let adt = cx.tcx.adt_def(item.owner_id.to_def_id());

        let variants = definition
            .variants
            .iter()
            .map(|variant| {
                let def_id = variant.def_id;
                let attributes = source_attributes
                    .as_ref()
                    .and_then(|source| source.variants.get(variant.ident.name.as_str()))
                    .cloned()
                    .unwrap_or_default();
                let definition = adt
                    .variants()
                    .iter()
                    .find(|definition| definition.def_id.as_local() == Some(def_id))?;
                let has_payload = !definition.fields.is_empty();
                let has_domain_payload = definition.fields.iter().any(|field| {
                    let field_type = cx.tcx.type_of(field.did).instantiate_identity();
                    !field_type.is_unit()
                        && !field_type.ty_adt_def().is_some_and(|field_definition| {
                            let definition = field_definition.did();
                            cx.tcx.crate_name(definition.krate) == sym::core
                                && cx.tcx.item_name(definition).as_str() == "PhantomData"
                        })
                });
                let implicit =
                    CaseStyle::apply(variant.ident.name.as_str(), type_attributes.from_name);
                let mut parser_names = attributes.serializations.clone();
                if let Some(output) = &attributes.to_string {
                    parser_names.push(output.clone());
                }
                if parser_names.is_empty() {
                    parser_names.push(implicit.clone());
                }
                let preferred = attributes.to_string.clone().unwrap_or_else(|| {
                    attributes
                        .serializations
                        .iter()
                        .max_by_key(|serialization| serialization.len())
                        .cloned()
                        .unwrap_or(implicit)
                });
                let preferred_name = format!(
                    "{}{}{}",
                    type_attributes.prefix.as_deref().unwrap_or_default(),
                    preferred,
                    type_attributes.suffix.as_deref().unwrap_or_default()
                );
                Some(VariantContract {
                    def_id,
                    span: variant.span,
                    name: variant.ident.name,
                    parser_names,
                    preferred_name,
                    is_disabled: attributes.is_disabled,
                    is_default_capture: attributes.is_default_capture,
                    is_ascii_case_insensitive: attributes
                        .is_ascii_case_insensitive
                        .unwrap_or(type_attributes.is_ascii_case_insensitive),
                    has_payload,
                    has_domain_payload,
                    is_deprecated: cx
                        .tcx
                        .lookup_deprecation_entry(variant.def_id.to_def_id())
                        .is_some(),
                    message: attributes.message,
                    detailed_message: attributes.detailed_message,
                    properties: attributes.properties,
                    has_explicit_output: attributes.to_string.is_some(),
                    has_explicit_string_payload: attributes.has_explicit_string_payload,
                })
            })
            .collect::<Option<Vec<_>>>()?;

        Some(Self {
            def_id: item.owner_id.def_id,
            owner: item.hir_id(),
            span: item.span,
            source_span: source_attributes
                .as_ref()
                .map_or(item.span, |source| source.span),
            name: item.kind.ident()?.name,
            is_public: cx.tcx.visibility(item.owner_id.def_id).is_public(),
            variants,
            derives: HashSet::new(),
            generated_discriminant: None,
            is_discriminant_external_schema: false,
        })
    }

    /// Returns whether this enum has one generated Strum contract.
    pub(crate) fn derives(&self, derive: StrumDerive) -> bool {
        self.derives.contains(&derive)
    }

    /// Returns active variants for derives that honor `#[strum(disabled)]`.
    pub(crate) fn enabled_variants(&self) -> impl Iterator<Item = &VariantContract> {
        self.variants.iter().filter(|variant| !variant.is_disabled)
    }

    /// Returns whether any variant already carries Strum message metadata.
    pub(crate) fn has_authored_message_metadata(&self) -> bool {
        self.variants
            .iter()
            .any(|variant| variant.message.is_some() || variant.detailed_message.is_some())
    }

    /// Returns whether the named Strum property already owns this metadata key.
    pub(crate) fn has_authored_property(&self, name: &str) -> bool {
        self.variants
            .iter()
            .flat_map(|variant| &variant.properties)
            .any(|property| property.name == name)
    }
}

// -----------------------------------------------------------------------------
// VariantContract: Effective behavior for one enum variant
// -----------------------------------------------------------------------------

/// Effective Strum attributes for one compiled enum variant.
#[derive(Clone)]
#[expect(
    clippy::struct_excessive_bools,
    reason = "these flags model independent authored Strum attributes and variant shapes"
)]
pub struct VariantContract {
    /// Compiler identity used to correlate this variant with generated implementations.
    pub(crate) def_id: LocalDefId,
    /// Authored declaration or expression range used as the diagnostic anchor.
    pub(crate) span: Span,
    /// Authored enum or variant name involved in the Strum contract.
    pub(crate) name: Symbol,
    /// Every spelling accepted by the generated `EnumString` parser.
    pub(crate) parser_names: Vec<String>,
    /// Spelling selected by Strum when a generated API emits this variant's name.
    pub(crate) preferred_name: String,
    /// Whether Strum excludes this variant from generated parsing and iteration.
    pub(crate) is_disabled: bool,
    /// Whether this variant captures otherwise unmatched parser input.
    pub(crate) is_default_capture: bool,
    /// Whether parser aliases are compared without ASCII case distinctions.
    pub(crate) is_ascii_case_insensitive: bool,
    /// Whether constructing this variant requires any payload value.
    pub(crate) has_payload: bool,
    /// Whether a payload field carries domain data rather than a marker default.
    pub(crate) has_domain_payload: bool,
    /// Whether the authored variant is deprecated and should be omitted from new APIs.
    pub(crate) is_deprecated: bool,
    /// Authored message participating in the contract.
    message: Option<String>,
    /// Longer user-facing message authored with `detailed_message`.
    detailed_message: Option<String>,
    /// Static key-value metadata authored with Strum properties.
    properties: Vec<StrumProperty>,
    /// Whether the author selected an explicit output spelling for this variant.
    pub(crate) has_explicit_output: bool,
    /// Whether `EnumString` invokes an authored constructor for every payload field.
    pub(crate) has_explicit_string_payload: bool,
}

// -----------------------------------------------------------------------------
// ContractCatalog: Crate-wide authored and generated evidence
// -----------------------------------------------------------------------------

/// Crate-wide authored enums plus generated Strum derive evidence.
#[derive(Default)]
pub struct ContractCatalog {
    /// Authored enum contracts keyed by their local declaration identity.
    contracts: HashMap<LocalDefId, EnumContract>,
    /// Derive macros that establish the generated behavior.
    derives: HashMap<LocalDefId, HashSet<StrumDerive>>,
    /// Generated discriminant enums awaiting association with their source enums.
    discriminants: Vec<GeneratedDiscriminant>,
    /// Types with manual Serde implementations that make their representation external.
    external_schema_types: HashSet<LocalDefId>,
}

impl ContractCatalog {
    /// Resolves the known Strum derive responsible for a generated item.
    fn derive_for(cx: &LateContext<'_>, span: Span) -> Option<StrumDerive> {
        span.macro_backtrace().find_map(|expansion| {
            let definition = expansion.macro_def_id?;
            (cx.tcx.crate_name(definition.krate).as_str() == "strum_macros")
                .then(|| StrumDerive::from_macro_name(cx.tcx.item_name(definition).as_str()))
                .flatten()
        })
    }

    /// Returns the completed authored contracts after associating generated derives.
    pub(crate) fn contracts(&self) -> Vec<EnumContract> {
        let mut contracts = self
            .contracts
            .values()
            .cloned()
            .map(|mut contract| {
                contract.derives = self
                    .derives
                    .get(&contract.def_id)
                    .cloned()
                    .unwrap_or_default();
                contract.generated_discriminant = self
                    .discriminants
                    .iter()
                    .find(|generated| contract.source_span.contains(generated.source_callsite))
                    .map(|generated| generated.def_id);
                contract.is_discriminant_external_schema = contract
                    .generated_discriminant
                    .is_some_and(|definition| self.external_schema_types.contains(&definition));
                contract
            })
            .collect::<Vec<_>>();
        contracts.sort_by_key(|contract| contract.span.lo());
        contracts
    }

    /// Finds the unique enum contract represented by an authored variant-name table.
    pub(crate) fn matching_string_table(
        &self,
        table: &StringTableCandidate,
    ) -> Option<EnumContract> {
        let mut matches = self.contracts().into_iter().filter(|contract| {
            table
                .enum_def
                .is_none_or(|enum_def| enum_def == contract.def_id)
                && table.values
                    == contract
                        .variants
                        .iter()
                        .map(|variant| variant.preferred_name.clone())
                        .collect::<Vec<_>>()
                && (table.enum_def.is_some()
                    || IdentifierTypeNames {
                        identifier: table.name.as_str(),
                        type_name: contract.name.as_str(),
                    }
                    .identifier_mentions_type())
        });
        let first = matches.next()?;
        matches.next().is_none().then_some(first)
    }

    /// Records types whose manual Serde implementation exposes a separate wire schema.
    fn record_external_schema_impl(&mut self, cx: &LateContext<'_>, item: &Item<'_>) {
        // Only implementation items can establish an external schema trait.
        let ItemKind::Impl(implementation) = item.kind else {
            return;
        };

        // Inherent implementations do not define a serialization contract.
        let Some(trait_def) = implementation
            .of_trait
            .and_then(|trait_ref| trait_ref.trait_ref.trait_def_id())
        else {
            return;
        };

        // Only Serde serialization traits expose a separate wire schema.
        if !matches!(
            cx.tcx.item_name(trait_def).as_str(),
            "Serialize" | "Deserialize"
        ) || !matches!(
            cx.tcx.crate_name(trait_def.krate).as_str(),
            "serde" | "serde_core"
        ) {
            return;
        }

        // Only local nominal types can be recorded as schema-bearing.
        let Some(definition) = cx
            .tcx
            .type_of(item.owner_id)
            .instantiate_identity()
            .ty_adt_def()
            .and_then(|definition| definition.did().as_local())
        else {
            return;
        };
        self.external_schema_types.insert(definition);
    }

    /// Associates macro-generated implementations and discriminants with source enums.
    fn record_generated_item(&mut self, cx: &LateContext<'_>, item: &Item<'_>) {
        // Items outside a recognized Strum derive have no generated contract.
        let Some(derive) = Self::derive_for(cx, item.span) else {
            return;
        };

        match item.kind {
            ItemKind::Impl(_) => {
                // Generated implementations without a local enum target are irrelevant.
                let Some(enum_def) = cx
                    .tcx
                    .type_of(item.owner_id)
                    .instantiate_identity()
                    .ty_adt_def()
                    .and_then(|definition| definition.did().as_local())
                else {
                    return;
                };
                self.derives.entry(enum_def).or_default().insert(derive);
            }
            ItemKind::Enum(..) if derive == StrumDerive::EnumDiscriminants => {
                self.discriminants.push(GeneratedDiscriminant {
                    def_id: item.owner_id.def_id,
                    source_callsite: item.span.source_callsite(),
                });
            }
            _ => {}
        }
    }

    /// Records authored enums and Strum-generated items.
    pub(crate) fn check_item(&mut self, cx: &LateContext<'_>, item: &Item<'_>) {
        self.record_external_schema_impl(cx, item);

        // Macro expansion items need generated-contract association instead of source parsing.
        if item.span.from_expansion() {
            self.record_generated_item(cx, item);
            return;
        }

        // Non-enum authored items have no Strum contract to retain.
        let Some(contract) = EnumContract::from_item(cx, item) else {
            return;
        };
        self.contracts.insert(contract.def_id, contract);
    }
}

// -----------------------------------------------------------------------------
// GeneratedDiscriminant: Source-to-discriminant association
// -----------------------------------------------------------------------------

/// Generated discriminant type associated with its source enum.
struct GeneratedDiscriminant {
    /// Compiler identity of the generated discriminant enum.
    def_id: LocalDefId,
    /// Derive invocation range used to associate the generated enum with its source.
    source_callsite: Span,
}

// -----------------------------------------------------------------------------
// CaseStyle: Strum case-conversion vocabulary
// -----------------------------------------------------------------------------

/// Case conversions accepted by Strum's `serialize_all` attribute.
#[derive(Clone, Copy)]
enum CaseStyle {
    /// Lower camel case, such as `variantName`.
    Camel,
    /// Lower kebab case, such as `variant-name`.
    Kebab,
    /// Lowercase with no word separator.
    Lower,
    /// Lower snake case under Strum's `mixed_case` spelling.
    Mixed,
    /// Upper camel case, such as `VariantName`.
    Pascal,
    /// Upper kebab case, such as `VARIANT-NAME`.
    ScreamingKebab,
    /// Upper snake case, such as `VARIANT_NAME`.
    ScreamingSnake,
    /// Lower snake case, such as `variant_name`.
    Snake,
    /// Space-separated title case, such as `Variant Name`.
    Title,
    /// Hyphenated title case, such as `Variant-Name`.
    Train,
    /// Uppercase with no word separator.
    Upper,
}

impl CaseStyle {
    /// Parses Strum's authored case-conversion vocabulary.
    fn from_name(value: &str) -> Option<Self> {
        match value {
            "camelCase" => Some(Self::Camel),
            "kebab-case" => Some(Self::Kebab),
            "lowercase" => Some(Self::Lower),
            "mixed_case" => Some(Self::Mixed),
            "PascalCase" => Some(Self::Pascal),
            "SCREAMING-KEBAB-CASE" => Some(Self::ScreamingKebab),
            "SCREAMING_SNAKE_CASE" => Some(Self::ScreamingSnake),
            "snake_case" => Some(Self::Snake),
            "title_case" => Some(Self::Title),
            "Train-Case" => Some(Self::Train),
            "UPPERCASE" => Some(Self::Upper),
            _ => None,
        }
    }

    /// Applies the selected conversion to an authored variant name.
    fn apply(value: &str, style: Option<Self>) -> String {
        match style {
            Some(Self::Camel) => value.to_lower_camel_case(),
            Some(Self::Kebab) => value.to_kebab_case(),
            Some(Self::Lower) => value.to_lowercase(),
            Some(Self::Mixed | Self::Snake) => value.to_snake_case(),
            Some(Self::Pascal) => value.to_upper_camel_case(),
            Some(Self::ScreamingKebab) => value.to_shouty_kebab_case(),
            Some(Self::ScreamingSnake) => value.to_shouty_snake_case(),
            Some(Self::Title) => value.to_title_case(),
            Some(Self::Train) => value.to_train_case(),
            Some(Self::Upper) => value.to_uppercase(),
            None => value.to_owned(),
        }
    }
}

// -----------------------------------------------------------------------------
// StrumAttributeValue: Nested attribute value parsing
// -----------------------------------------------------------------------------

/// Reads typed values from nested Strum attributes.
struct StrumAttributeValue;

impl StrumAttributeValue {
    /// Reads a required string value.
    fn string(meta: &ParseNestedMeta<'_>) -> syn::Result<String> {
        Ok(meta.value()?.parse::<LitStr>()?.value())
    }

    /// Reads a boolean flag, treating a bare flag as enabled.
    fn boolean(meta: &ParseNestedMeta<'_>) -> syn::Result<bool> {
        if meta.input.peek(Token![=]) {
            Ok(meta.value()?.parse::<LitBool>()?.value)
        } else {
            Ok(true)
        }
    }
}

// -----------------------------------------------------------------------------
// TypeAttributes: Type-level Strum policy
// -----------------------------------------------------------------------------

/// Parsed type-level attributes that transform every generated variant spelling.
#[derive(Clone, Default)]
struct TypeAttributes {
    /// Optional case conversion applied before per-variant overrides.
    from_name: Option<CaseStyle>,
    /// Default ASCII-insensitive parsing policy inherited by variants.
    is_ascii_case_insensitive: bool,
    /// Text prepended to generated spellings for every variant.
    prefix: Option<String>,
    /// Text appended to generated spellings for every variant.
    suffix: Option<String>,
}

impl TypeAttributes {
    /// Parses type-wide naming and parser policy from Strum attributes.
    fn from_attrs(attributes: &[syn::Attribute]) -> Self {
        let mut output = Self::default();
        for attribute in attributes {
            if !attribute.path().is_ident("strum") {
                continue;
            }
            let parsing = attribute.parse_nested_meta(|meta| {
                if meta.path.is_ident("serialize_all") {
                    output.from_name = CaseStyle::from_name(&StrumAttributeValue::string(&meta)?);
                } else if meta.path.is_ident("ascii_case_insensitive") {
                    output.is_ascii_case_insensitive = StrumAttributeValue::boolean(&meta)?;
                } else if meta.path.is_ident("prefix") {
                    output.prefix = Some(StrumAttributeValue::string(&meta)?);
                } else if meta.path.is_ident("suffix") {
                    output.suffix = Some(StrumAttributeValue::string(&meta)?);
                }
                Ok(())
            });

            // Malformed Strum metadata cannot contribute a reliable type-wide policy.
            if parsing.is_err() {
                return output;
            }
        }
        output
    }
}

// -----------------------------------------------------------------------------
// VariantAttributes: Variant-level Strum policy
// -----------------------------------------------------------------------------

/// Parsed per-variant overrides for generated parsing, display, and metadata.
#[derive(Clone, Default)]
struct VariantAttributes {
    /// Explicit aliases accepted by generated parsers.
    serializations: Vec<String>,
    /// Explicit spelling selected for generated output.
    to_string: Option<String>,
    /// Whether generated Strum APIs exclude this variant.
    is_disabled: bool,
    /// Whether this variant captures parser input unmatched by explicit aliases.
    is_default_capture: bool,
    /// Per-variant override for ASCII-insensitive parsing.
    is_ascii_case_insensitive: Option<bool>,
    /// Authored message participating in the contract.
    message: Option<String>,
    /// Longer runtime message authored for this variant.
    detailed_message: Option<String>,
    /// Static metadata entries authored for this variant.
    properties: Vec<StrumProperty>,
    /// Whether parsing uses authored payload constructors instead of `Default`.
    has_explicit_string_payload: bool,
}

impl VariantAttributes {
    /// Parses per-variant naming, message, and metadata overrides.
    fn from_attrs(attributes: &[syn::Attribute]) -> Self {
        let mut output = Self::default();
        for attribute in attributes {
            if !attribute.path().is_ident("strum") {
                continue;
            }
            let parsing = attribute.parse_nested_meta(|meta| {
                if meta.path.is_ident("serialize") {
                    output
                        .serializations
                        .push(StrumAttributeValue::string(&meta)?);
                } else if meta.path.is_ident("to_string") {
                    output.to_string = Some(StrumAttributeValue::string(&meta)?);
                } else if meta.path.is_ident("disabled") {
                    output.is_disabled = true;
                } else if meta.path.is_ident("default") {
                    output.is_default_capture = true;
                } else if meta.path.is_ident("default_with") {
                    let _constructor = StrumAttributeValue::string(&meta)?;
                    output.has_explicit_string_payload = true;
                } else if meta.path.is_ident("ascii_case_insensitive") {
                    output.is_ascii_case_insensitive = Some(StrumAttributeValue::boolean(&meta)?);
                } else if meta.path.is_ident("message") {
                    output.message = Some(StrumAttributeValue::string(&meta)?);
                } else if meta.path.is_ident("detailed_message") {
                    output.detailed_message = Some(StrumAttributeValue::string(&meta)?);
                } else if meta.path.is_ident("props") {
                    meta.parse_nested_meta(|property| {
                        // Unnamed properties cannot provide a stable metadata key.
                        let Some(name) = property.path.get_ident() else {
                            return Ok(());
                        };
                        output.properties.push(StrumProperty {
                            name: name.to_string(),
                            _value: StrumAttributeValue::string(&property)?,
                        });
                        Ok(())
                    })?;
                }
                Ok(())
            });

            // Malformed Strum metadata cannot contribute reliable variant policy.
            if parsing.is_err() {
                return output;
            }
        }
        output
    }
}

// -----------------------------------------------------------------------------
// SourceAttributes: Parsed authored Strum policy
// -----------------------------------------------------------------------------

/// Complete authored Strum policy recovered from source-level attributes.
struct SourceAttributes {
    /// Resolved type involved in the contract.
    ty: TypeAttributes,
    /// Variants participating in the analyzed contract.
    variants: HashMap<String, VariantAttributes>,
    /// Authored declaration or expression range used as the diagnostic anchor.
    span: Span,
}

impl SourceAttributes {
    /// Recovers this contract from one authored declaration.
    fn from_item(cx: &LateContext<'_>, item: &Item<'_>) -> Option<Self> {
        let EnumSource { source, span } = EnumSource::for_item(cx, item)?;
        let parsed = match syn::parse_str::<syn::ItemEnum>(&source) {
            Ok(parsed) => parsed,
            // Source unavailable from the compiler cannot be parsed for outer attributes.
            Err(_error) => return None,
        };

        Some(Self {
            ty: TypeAttributes::from_attrs(&parsed.attrs),
            variants: parsed
                .variants
                .into_iter()
                .map(|variant| {
                    let mut attributes = VariantAttributes::from_attrs(&variant.attrs);
                    if let syn::Fields::Named(fields) = &variant.fields {
                        attributes.has_explicit_string_payload = fields.named.iter().all(|field| {
                            field.attrs.iter().any(|attribute| {
                                // Non-Strum attributes cannot define default payload construction.
                                if !attribute.path().is_ident("strum") {
                                    return false;
                                }
                                let mut found = false;
                                let parsing = attribute.parse_nested_meta(|meta| {
                                    if meta.path.is_ident("default_with") {
                                        let _constructor = StrumAttributeValue::string(&meta)?;
                                        found = true;
                                    }
                                    Ok(())
                                });
                                parsing.is_ok() && found
                            })
                        });
                    }
                    (variant.ident.to_string(), attributes)
                })
                .collect(),
            span,
        })
    }
}

// -----------------------------------------------------------------------------
// EnumSource: Attribute-inclusive enum source recovery
// -----------------------------------------------------------------------------

/// Authored enum source together with the span that includes its attributes.
struct EnumSource {
    /// Source text parsed for Strum attributes.
    source: String,
    /// Span corresponding to the recovered source.
    span: Span,
}

impl EnumSource {
    /// Recovers an enum declaration together with its outer attributes.
    fn for_item(cx: &LateContext<'_>, item: &Item<'_>) -> Option<Self> {
        let source_map = cx.tcx.sess.source_map();
        let item_source = match source_map.span_to_snippet(item.span) {
            Ok(source) => source,
            // Source unavailable from the compiler cannot be parsed for outer attributes.
            Err(_error) => return None,
        };
        let location = source_map.lookup_char_pos(item.span.lo());
        let file_source = location.file.src.as_deref()?;

        // Offsets outside the source file cannot delimit the attributed enum source.
        let offset = match usize::try_from(item.span.lo().0.checked_sub(location.file.start_pos.0)?)
        {
            Ok(offset) => offset,
            // Offsets outside the source file cannot delimit the attributed enum source.
            Err(_error) => return None,
        };
        let bytes = file_source.as_bytes();
        let mut start = offset;

        loop {
            while start > 0 && bytes[start - 1].is_ascii_whitespace() {
                start -= 1;
            }
            if start == 0 || bytes[start - 1] != b']' {
                break;
            }
            let mut cursor = start - 1;
            let mut depth = 1_u32;
            while cursor > 0 && depth > 0 {
                cursor -= 1;
                match bytes[cursor] {
                    b']' => depth += 1,
                    b'[' => depth -= 1,
                    _ => {}
                }
            }
            if depth != 0 || cursor == 0 || bytes[cursor - 1] != b'#' {
                break;
            }
            start = cursor - 1;
        }

        // Source positions that exceed rustc's byte range cannot form a span.
        let source_offset = match u32::try_from(start) {
            Ok(offset) => offset,
            // Source positions that exceed rustc's byte range cannot form a span.
            Err(_error) => return None,
        };
        let source_lo = rustc_span::BytePos(location.file.start_pos.0 + source_offset);

        Some(Self {
            source: format!("{}{}", &file_source[start..offset], item_source),
            span: item.span.with_lo(source_lo),
        })
    }
}

// -----------------------------------------------------------------------------
// StrumAssociatedItem: Generated associated-contract recognition
// -----------------------------------------------------------------------------

/// Trait and item names that identify one Strum associated contract.
pub struct StrumAssociatedItem<'name> {
    /// Strum trait owning the associated item.
    pub(crate) trait_name: &'name str,
    /// Associated function or constant name.
    pub(crate) item_name: &'name str,
}

impl StrumAssociatedItem<'_> {
    /// Resolves the enum type in a `Type::ITEM` path owned by this Strum contract.
    pub(crate) fn enum_definition(
        &self,
        cx: &LateContext<'_>,
        expression: &Expr<'_>,
    ) -> Option<LocalDefId> {
        // Only paths can refer to a generated associated Strum item.
        let ExprKind::Path(path) = expression.kind else {
            return None;
        };
        let definition = cx.qpath_res(&path, expression.hir_id).opt_def_id()?;

        // Only associated functions and constants can be the queried Strum contract.
        if !matches!(
            cx.tcx.def_kind(definition),
            DefKind::AssocFn | DefKind::AssocConst { .. }
        ) {
            return None;
        }

        let contract_definition = cx
            .tcx
            .associated_item(definition)
            .trait_item_def_id()
            .unwrap_or(definition);

        // Other associated items do not match the requested Strum contract member.
        if cx.tcx.item_name(contract_definition).as_str() != self.item_name {
            return None;
        }
        let path_name = cx.tcx.def_path_str(contract_definition);

        // Items outside the expected Strum trait are unrelated associated members.
        if !path_name.contains("strum") || !path_name.contains(self.trait_name) {
            return None;
        }

        // Only type-relative paths expose the enum receiver type.
        let QPath::TypeRelative(ty, _) = path else {
            return None;
        };

        cx.typeck_results()
            .node_type(ty.hir_id)
            .ty_adt_def()?
            .did()
            .as_local()
    }
}
