extern crate rustc_ast;
extern crate rustc_hir;
extern crate rustc_lint;
extern crate rustc_span;

use std::num::TryFromIntError;

use rustc_hir::def::{CtorOf, DefKind, Res};
use rustc_hir::def_id::{DefId, LocalDefId};
use rustc_hir::intravisit::{self, Visitor};
use rustc_hir::{
    BodyId, ConstItemRhs, Expr, ExprKind, ImplItem, ImplItemKind, Item, ItemKind, Node,
};
use rustc_lint::LateContext;
use rustc_span::{Span, Symbol};
use serde::Deserialize;

// -----------------------------------------------------------------------------
// Collection: Configured generated API surface
// -----------------------------------------------------------------------------

/// Provider values accepted by the enum collection conflict knob.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum CollectionProvider {
    /// Iteration generated by Strum's `EnumIter` derive.
    StrumEnumIter,
    /// Static arrays generated by Strum's `VariantArray` derive.
    StrumVariantArray,
}

/// Authored API shape reproduced by a Strum enumeration derive.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CollectionSurface {
    /// A fixed array or slice containing every variant.
    Static,
    /// An `IntoIterator` implementation yielding every variant.
    Iterator,
}

/// Returns whether the crate can use Strum derives as a remediation.
fn strum_derives_available(cx: &LateContext<'_>) -> bool {
    cx.tcx.sess.opts.externs.get("strum").is_some()
}

/// Removes expression wrappers that do not change value semantics.
const fn peel_transparent<'hir>(mut expression: &'hir Expr<'hir>) -> &'hir Expr<'hir> {
    loop {
        expression = match expression.kind {
            ExprKind::Block(block, None) if block.stmts.is_empty() => {
                let Some(inner) = block.expr else {
                    return expression;
                };
                inner
            }
            ExprKind::AddrOf(_, _, inner) | ExprKind::DropTemps(inner) => inner,
            _ => return expression,
        };
    }
}

/// Resolves a directly referenced constant, static, or zero-argument function body.
fn forwarded_body(cx: &LateContext<'_>, expression: &Expr<'_>) -> Option<BodyId> {
    let definition = match expression.kind {
        ExprKind::Path(path) => match cx.qpath_res(&path, expression.hir_id) {
            Res::Def(
                DefKind::Const { .. } | DefKind::AssocConst { .. } | DefKind::Static { .. },
                definition,
            ) => definition.as_local()?,
            _ => return None,
        },
        ExprKind::Call(callee, []) => {
            let ExprKind::Path(path) = peel_transparent(callee).kind else {
                return None;
            };
            match cx.qpath_res(&path, callee.hir_id) {
                Res::Def(DefKind::Fn | DefKind::AssocFn, definition) => definition.as_local()?,
                _ => return None,
            }
        }
        _ => return None,
    };

    match cx.tcx.hir_node_by_def_id(definition) {
        Node::Item(item) => match item.kind {
            ItemKind::Const(_, _, _, ConstItemRhs::Body(body))
            | ItemKind::Static(_, _, _, body)
            | ItemKind::Fn { body, .. } => Some(body),
            _ => None,
        },
        Node::ImplItem(item) => match item.kind {
            ImplItemKind::Const(_, ConstItemRhs::Body(body)) | ImplItemKind::Fn(_, body) => {
                Some(body)
            }
            _ => None,
        },
        _ => None,
    }
}

/// Resolves an expression that names one local unit variant.
fn unit_variant(cx: &LateContext<'_>, expression: &Expr<'_>) -> Option<LocalDefId> {
    let ExprKind::Path(path) = peel_transparent(expression).kind else {
        return None;
    };
    let Res::Def(DefKind::Ctor(CtorOf::Variant, _), constructor) =
        cx.qpath_res(&path, expression.hir_id)
    else {
        return None;
    };
    cx.tcx.opt_local_parent(constructor.as_local()?)
}

// -----------------------------------------------------------------------------
// VariantCollector: Exact unit-variant sequence recovery
// -----------------------------------------------------------------------------

/// Collects direct unit-variant expressions in authored order.
struct VariantCollector<'cx, 'tcx> {
    /// Compiler context used to resolve each expression to its variant definition.
    cx: &'cx LateContext<'tcx>,
    /// Variants participating in the analyzed contract.
    variants: Vec<LocalDefId>,
    /// Whether authored runtime logic prevents this sequence from being an exact table.
    is_invalid: bool,
}

impl<'cx, 'tcx> VariantCollector<'cx, 'tcx> {
    /// Starts ordered variant recovery for the active compiler context.
    const fn new(cx: &'cx LateContext<'tcx>) -> Self {
        Self {
            cx,
            variants: Vec::new(),
            is_invalid: false,
        }
    }
}

impl<'tcx> Visitor<'tcx> for VariantCollector<'_, 'tcx> {
    fn visit_expr(&mut self, expression: &'tcx Expr<'tcx>) {
        if let Some(variant) = unit_variant(self.cx, expression) {
            self.variants.push(variant);
            return;
        }
        if !expression.span.from_expansion() {
            self.is_invalid = true;
            return;
        }
        intravisit::walk_expr(self, expression);
    }
}

/// Resolves the local enum that owns a variant.
fn owning_enum(cx: &LateContext<'_>, variant: DefId) -> Option<LocalDefId> {
    cx.tcx.opt_local_parent(variant.as_local()?)
}

/// Returns whether per-variant Strum policy could change generated membership or order.
fn enum_has_strum_variant_attributes(cx: &LateContext<'_>, enum_def: LocalDefId) -> bool {
    let Node::Item(item) = cx.tcx.hir_node_by_def_id(enum_def) else {
        return true;
    };
    let ItemKind::Enum(_, _, definition) = item.kind else {
        return true;
    };
    let strum = Symbol::intern("strum");
    definition.variants.iter().any(|variant| {
        cx.tcx
            .hir_attrs(variant.hir_id)
            .iter()
            .any(|attribute| attribute.has_name(strum))
    })
}

/// Returns every unit variant when Strum can reproduce the enum's complete sequence.
fn eligible_unit_variants(cx: &LateContext<'_>, enum_def: LocalDefId) -> Option<Vec<LocalDefId>> {
    let definition = cx.tcx.adt_def(enum_def.to_def_id());
    if !definition.is_enum()
        || definition
            .variants()
            .iter()
            .any(|variant| !variant.fields.is_empty())
        || enum_has_strum_variant_attributes(cx, enum_def)
    {
        return None;
    }

    Some(
        definition
            .variants()
            .iter()
            .filter_map(|variant| variant.def_id.as_local())
            .collect(),
    )
}

/// Resolves the local enum targeted by the enclosing inherent implementation.
fn enclosing_inherent_enum(cx: &LateContext<'_>, hir_id: rustc_hir::HirId) -> Option<LocalDefId> {
    cx.tcx.hir_parent_iter(hir_id).find_map(|(_, node)| {
        let Node::Item(item) = node else { return None };
        let ItemKind::Impl(implementation) = item.kind else {
            return None;
        };
        if implementation.of_trait.is_some() {
            return None;
        }
        cx.tcx
            .type_of(item.owner_id)
            .instantiate_identity()
            .ty_adt_def()?
            .did()
            .as_local()
    })
}

/// Resolves the local enum targeted by an enclosing `IntoIterator` implementation.
fn enclosing_into_iterator_enum(
    cx: &LateContext<'_>,
    hir_id: rustc_hir::HirId,
) -> Option<LocalDefId> {
    cx.tcx.hir_parent_iter(hir_id).find_map(|(_, node)| {
        let Node::Item(item) = node else {
            return None;
        };
        let ItemKind::Impl(implementation) = item.kind else {
            return None;
        };
        let implementation_header = implementation.of_trait?;
        let Res::Def(DefKind::Trait, trait_definition) = implementation_header.trait_ref.path.res
        else {
            return None;
        };
        if cx.tcx.item_name(trait_definition).as_str() != "IntoIterator"
            || cx.tcx.crate_name(trait_definition.krate).as_str() != "core"
        {
            return None;
        }
        cx.tcx
            .type_of(item.owner_id)
            .instantiate_identity()
            .ty_adt_def()?
            .did()
            .as_local()
    })
}

/// Reads a non-negative integer literal without accepting computed values.
fn integer_literal(expression: &Expr<'_>) -> Result<Option<usize>, TryFromIntError> {
    let ExprKind::Lit(literal) = peel_transparent(expression).kind else {
        return Ok(None);
    };
    let rustc_ast::LitKind::Int(value, _) = literal.node else {
        return Ok(None);
    };

    usize::try_from(value.get()).map(Some)
}

// -----------------------------------------------------------------------------
// CountCandidate: Exact authored enum cardinality
// -----------------------------------------------------------------------------

/// Exact authored total count associated with one enum.
pub struct CountCandidate {
    /// Authored declaration or expression range used as the diagnostic anchor.
    pub(crate) span: Span,
    /// Declaration whose lint level governs this finding.
    pub(crate) owner: rustc_hir::HirId,
    /// Local enum definition that owns the analyzed contract.
    enum_def: LocalDefId,
    /// Whether replacement would change a public API.
    is_public_api: bool,
}

impl CountCandidate {
    /// Recovers a constant or method that returns the enum's exact cardinality.
    pub(crate) fn from_impl_item(cx: &LateContext<'_>, item: &ImplItem<'_>) -> Option<Self> {
        if item.span.from_expansion() || !strum_derives_available(cx) {
            return None;
        }

        let body = match item.kind {
            ImplItemKind::Const(_, ConstItemRhs::Body(body)) => body,
            ImplItemKind::Fn(signature, body) if signature.decl.inputs.is_empty() => body,
            _ => return None,
        };
        let enum_def = enclosing_inherent_enum(cx, item.hir_id())?;
        let count = match integer_literal(cx.tcx.hir_body(body).value) {
            Ok(Some(count)) => count,
            Ok(None) => return None,
            Err(_error) => return None,
        };

        if enum_has_strum_variant_attributes(cx, enum_def) {
            return None;
        }
        let expected = cx.tcx.adt_def(enum_def.to_def_id()).variants().len();

        (count == expected).then(|| Self {
            span: cx.tcx.hir_body(body).value.span,
            owner: item.hir_id(),
            enum_def,
            is_public_api: cx.tcx.visibility(item.owner_id.def_id).is_public(),
        })
    }

    /// Returns whether replacement would alter a public API.
    pub(crate) const fn is_public_api(&self) -> bool {
        self.is_public_api
    }

    /// Resolves the owning enum name used in diagnostics.
    pub(crate) fn enum_name(&self, cx: &LateContext<'_>) -> Symbol {
        cx.tcx.item_name(self.enum_def.to_def_id())
    }
}

/// Returns whether a collection expression was emitted by the standard `vec!` macro.
fn is_vec_expansion(cx: &LateContext<'_>, span: Span) -> bool {
    span.macro_backtrace().any(|expansion| {
        expansion.macro_def_id.is_some_and(|definition| {
            cx.tcx.item_name(definition).as_str() == "vec"
                && cx.tcx.crate_name(definition.krate).as_str() == "alloc"
        })
    })
}

// -----------------------------------------------------------------------------
// VariantSequence: Resolved authored variant sequence
// -----------------------------------------------------------------------------

/// Resolved enum variants paired with the collection interface that exposes them.
struct VariantSequence {
    /// Variants in the authored collection order.
    variants: Vec<LocalDefId>,
    /// Collection interface presented by the authored code.
    surface: CollectionSurface,
    /// Authored source span covering the collection.
    span: Span,
}

impl VariantSequence {
    /// Resolves a variant sequence through transparent collection helpers.
    fn resolve<'tcx>(
        cx: &LateContext<'tcx>,
        expression: &'tcx Expr<'tcx>,
        declared_surface: CollectionSurface,
        forwarding_depth: usize,
    ) -> Option<Self> {
        /// Maximum helper-call depth followed while resolving a variant sequence.
        const MAXIMUM_FORWARDING_DEPTH: usize = 4;

        if forwarding_depth > MAXIMUM_FORWARDING_DEPTH {
            return None;
        }
        let expression = peel_transparent(expression);

        if let ExprKind::Array(elements) = expression.kind {
            let variants = elements
                .iter()
                .map(|element| unit_variant(cx, element))
                .collect::<Option<Vec<_>>>()?;

            return Some(Self {
                variants,
                surface: declared_surface,
                span: expression.span.source_callsite(),
            });
        }

        if let ExprKind::MethodCall(segment, receiver, arguments, _) = expression.kind
            && arguments.is_empty()
            && matches!(
                segment.ident.name.as_str(),
                "iter" | "into_iter" | "copied" | "cloned" | "collect"
            )
        {
            let sequence =
                Self::resolve(cx, receiver, CollectionSurface::Iterator, forwarding_depth)?;
            return Some(Self {
                variants: sequence.variants,
                surface: CollectionSurface::Iterator,
                span: sequence.span,
            });
        }

        if let Some(body) = forwarded_body(cx, expression) {
            let sequence = Self::resolve(
                cx,
                cx.tcx.hir_body(body).value,
                declared_surface,
                forwarding_depth + 1,
            )?;
            return Some(Self {
                variants: sequence.variants,
                surface: sequence.surface,
                span: expression.span.source_callsite(),
            });
        }

        if is_vec_expansion(cx, expression.span) {
            let mut collector = VariantCollector::new(cx);
            collector.visit_expr(expression);
            if !collector.is_invalid && !collector.variants.is_empty() {
                return Some(Self {
                    variants: collector.variants,
                    surface: declared_surface,
                    span: expression.span.source_callsite(),
                });
            }
        }

        None
    }
}

// -----------------------------------------------------------------------------
// CollectionCandidate: Complete authored enum collections
// -----------------------------------------------------------------------------

/// Exact exhaustive unit-enum collection found in authored code.
pub struct CollectionCandidate {
    /// Authored declaration or expression range used as the diagnostic anchor.
    pub(crate) span: Span,
    /// Declaration whose lint level governs this finding.
    pub(crate) owner: rustc_hir::HirId,
    /// Local enum definition that owns the analyzed contract.
    enum_def: LocalDefId,
    /// Authored array, slice, vector, or iterator interface exposed by the declaration.
    surface: CollectionSurface,
    /// Whether replacement would change a public API.
    is_public_api: bool,
}

impl CollectionCandidate {
    /// Recovers this contract from one authored declaration.
    pub(crate) fn from_item(cx: &LateContext<'_>, item: &Item<'_>) -> Option<Self> {
        if item.span.from_expansion() {
            return None;
        }

        let (body, surface) = match item.kind {
            ItemKind::Const(_, _, _, ConstItemRhs::Body(body))
            | ItemKind::Static(_, _, _, body) => (body, CollectionSurface::Static),
            ItemKind::Fn { sig, body, .. } if sig.decl.inputs.is_empty() => {
                (body, CollectionSurface::Iterator)
            }
            _ => return None,
        };

        Self::from_body(cx, body, item.hir_id(), surface, item.owner_id.def_id)
    }

    /// Recovers a static collection or iterator that yields every variant in order.
    pub(crate) fn from_impl_item(cx: &LateContext<'_>, item: &ImplItem<'_>) -> Option<Self> {
        if item.span.from_expansion() {
            return None;
        }
        let into_iterator_enum = enclosing_into_iterator_enum(cx, item.hir_id());

        let (body, surface) = match item.kind {
            ImplItemKind::Const(_, ConstItemRhs::Body(body)) => (body, CollectionSurface::Static),
            ImplItemKind::Fn(signature, body) if signature.decl.inputs.is_empty() => {
                (body, CollectionSurface::Iterator)
            }
            ImplItemKind::Fn(signature, body)
                if signature.decl.inputs.len() == 1 && into_iterator_enum.is_some() =>
            {
                (body, CollectionSurface::Iterator)
            }
            _ => return None,
        };

        let candidate = Self::from_body(cx, body, item.hir_id(), surface, item.owner_id.def_id)?;
        if into_iterator_enum.is_some_and(|enum_def| enum_def != candidate.enum_def) {
            return None;
        }
        Some(candidate)
    }

    /// Recovers a complete ordered variant sequence from one function body.
    fn from_body(
        cx: &LateContext<'_>,
        body_id: BodyId,
        owner: rustc_hir::HirId,
        declared_surface: CollectionSurface,
        definition: LocalDefId,
    ) -> Option<Self> {
        if !strum_derives_available(cx) {
            return None;
        }
        let expression = cx.tcx.hir_body(body_id).value;
        let VariantSequence {
            variants,
            surface,
            span,
        } = VariantSequence::resolve(cx, expression, declared_surface, 0)?;
        let enum_def = owning_enum(cx, variants.first()?.to_def_id())?;

        if variants
            .iter()
            .any(|variant| owning_enum(cx, variant.to_def_id()) != Some(enum_def))
        {
            return None;
        }
        let expected = eligible_unit_variants(cx, enum_def)?;

        if variants != expected {
            return None;
        }

        Some(Self {
            span,
            owner,
            enum_def,
            surface,
            is_public_api: cx.tcx.visibility(definition).is_public(),
        })
    }

    /// Lists framework providers available in the current compilation.
    pub(crate) const fn providers(&self) -> &'static [CollectionProvider] {
        match self.surface {
            CollectionSurface::Static => &[
                CollectionProvider::StrumEnumIter,
                CollectionProvider::StrumVariantArray,
            ],
            CollectionSurface::Iterator => &[CollectionProvider::StrumEnumIter],
        }
    }

    /// Resolves the configured provider when several implementations are available.
    pub(crate) fn selected(
        &self,
        configured: Option<CollectionProvider>,
    ) -> Option<CollectionProvider> {
        let providers = self.providers();
        if providers.len() == 1 {
            return providers.first().copied();
        }
        configured.filter(|provider| providers.contains(provider))
    }

    /// Returns whether replacement would alter a public API.
    pub(crate) const fn is_public_api(&self) -> bool {
        self.is_public_api
    }

    /// Resolves the owning enum name used in diagnostics.
    pub(crate) fn enum_name(&self, cx: &LateContext<'_>) -> Symbol {
        cx.tcx.item_name(self.enum_def.to_def_id())
    }
}
