//! UI regression tests for every default-configuration lint fixture.

const CROSS_CUTTING_LINT_ALLOWS: [&str; 98] = [
    "-A",
    "ad_hoc_collection_construction",
    "-A",
    "ad_hoc_conversions",
    "-A",
    "ad_hoc_equality",
    "-A",
    "ad_hoc_error_interfaces",
    "-A",
    "ad_hoc_formatting",
    "-A",
    "ad_hoc_iterators",
    "-A",
    "ad_hoc_ordering",
    "-A",
    "ad_hoc_string_parsers",
    "-A",
    "ambiguous_primitive_parameters",
    "-A",
    "bare_tuple_types",
    "-A",
    "bidirectional_module_dependencies",
    "-A",
    "boolean_function_arguments",
    "-A",
    "constructor_like_free_functions",
    "-A",
    "deeply_nested_control_flow",
    "-A",
    "discarded_results",
    "-A",
    "duplicate_section_divider_prefixes",
    "-A",
    "fallible_values_replaced_with_defaults",
    "-A",
    "foreign_type_method_like_free_functions",
    "-A",
    "incoherent_extension_traits",
    "-A",
    "incoherent_type_family_names",
    "-A",
    "implicit_first_wins_deduplication",
    "-A",
    "long_method_chains",
    "-A",
    "malformed_code_phase_comments",
    "-A",
    "malformed_section_dividers",
    "-A",
    "mismatched_section_divider_prefixes",
    "-A",
    "missing_code_phase_comments",
    "-A",
    "missing_section_dividers",
    "-A",
    "needless_delegating_types",
    "-A",
    "needlessly_nested_control_flow",
    "-A",
    "nested_tuple_types",
    "-A",
    "non_defining_module_reexports",
    "-A",
    "noncanonical_restricted_visibility",
    "-A",
    "non_adjacent_extension_trait_impls",
    "-A",
    "overloaded_declaration_sections",
    "-A",
    "oversized_match_arms",
    "-A",
    "positional_aggregate_fields",
    "-A",
    "repeated_identical_statements",
    "-A",
    "results_converted_to_options",
    "-A",
    "revalidated_string_parameters",
    "-A",
    "single_implementation_traits",
    "-A",
    "stringly_typed_domain_function_families",
    "-A",
    "unconsumed_generic_abstractions",
    "-A",
    "undocumented_items",
    "-A",
    "unencapsulated_binary_enum_classification",
    "-A",
    "unnamed_policy_literals",
    "-A",
    "unnecessarily_broad_visibility",
    "-A",
    "unseparated_associated_items",
    "-A",
    "unparenthesized_mixed_boolean_operators",
    "-A",
    "visibility_required_only_by_tests",
];

const FIXTURE_LOCAL_LINT_ALLOWS: [&str; 20] = [
    "-A",
    "bool_fields_without_predicate_prefix",
    "-A",
    "collection_method_like_free_functions",
    "-A",
    "cross_file_struct_impls",
    "-A",
    "invalid_barrel_file_items",
    "-A",
    "method_like_free_functions",
    "-A",
    "misordered_inherent_impl_items",
    "-A",
    "misordered_module_declarations",
    "-A",
    "misordered_type_declarations",
    "-A",
    "needless_function_wrappers",
    "-A",
    "non_adjacent_struct_impls",
];

/// Runs every default-configuration UI fixture against the lint library.
#[test]
fn ui() {
    dylint_testing::ui::Test::src_base(env!("CARGO_PKG_NAME"), "ui/core")
        .rustc_flags(CROSS_CUTTING_LINT_ALLOWS)
        .run();
}

/// Runs dependency-aware Leptos fixtures against a library built with its default features.
#[cfg(feature = "leptos")]
#[test]
fn leptos_ui() {
    dylint_testing::ui::Test::example(env!("CARGO_PKG_NAME"), "boolean_component_props")
        .rustc_flags(CROSS_CUTTING_LINT_ALLOWS)
        .rustc_flags(FIXTURE_LOCAL_LINT_ALLOWS)
        .run();
}
