//! UI regression tests for every default-configuration lint fixture.

const CROSS_CUTTING_LINT_ALLOWS: [&str; 64] = [
    "-A",
    "ad_hoc_string_parsers",
    "-A",
    "ambiguous_primitive_parameters",
    "-A",
    "bare_tuple_types",
    "-A",
    "bidirectional_module_dependencies",
    "-A",
    "boolean_function_arguments",
    "-A",
    "constructor_like_free_functions",
    "-A",
    "deeply_nested_control_flow",
    "-A",
    "duplicate_section_divider_prefixes",
    "-A",
    "foreign_type_method_like_free_functions",
    "-A",
    "incoherent_extension_traits",
    "-A",
    "incoherent_type_family_names",
    "-A",
    "implicit_first_wins_deduplication",
    "-A",
    "long_method_chains",
    "-A",
    "malformed_code_phase_comments",
    "-A",
    "malformed_section_dividers",
    "-A",
    "mismatched_section_divider_prefixes",
    "-A",
    "missing_code_phase_comments",
    "-A",
    "missing_section_dividers",
    "-A",
    "nested_tuple_types",
    "-A",
    "non_defining_module_reexports",
    "-A",
    "non_adjacent_extension_trait_impls",
    "-A",
    "needlessly_nested_control_flow",
    "-A",
    "overloaded_declaration_sections",
    "-A",
    "oversized_match_arms",
    "-A",
    "positional_aggregate_fields",
    "-A",
    "repeated_identical_statements",
    "-A",
    "revalidated_string_parameters",
    "-A",
    "stringly_typed_domain_function_families",
    "-A",
    "undocumented_items",
    "-A",
    "unencapsulated_binary_enum_classification",
    "-A",
    "unseparated_associated_items",
    "-A",
    "unparenthesized_mixed_boolean_operators",
];

/// Runs every default-configuration UI fixture against the lint library.
#[test]
fn ui() {
    dylint_testing::ui::Test::src_base(env!("CARGO_PKG_NAME"), "ui")
        .rustc_flags(CROSS_CUTTING_LINT_ALLOWS)
        .run();
}
