extern crate rustc_errors;
extern crate rustc_hir;
extern crate rustc_span;

use std::borrow::Cow;

use convert_case::{Case, Casing};
use rustc_errors::DiagDecorator;
use rustc_hir::def::{CtorOf, DefKind, Res};
use rustc_hir::def_id::DefId;
use rustc_hir::{Expr, ExprKind};
use rustc_lint::{LateContext, LateLintPass, LintContext};
use rustc_span::Span;

use crate::utils::diagnostic::LateViolation;

// -----------------------------------------------------------------------------
// Violation: Public generated accessor that can panic
// -----------------------------------------------------------------------------

/// Generated accessor call whose receiver variant is not statically guaranteed.
struct Violation {
    /// Authored declaration or expression range used as the diagnostic anchor.
    span: Span,
    /// Generated accessor whose precondition is violated at this call site.
    method: String,
}

impl LateViolation for Violation {
    fn primary_message(&self) -> Cow<'_, str> {
        Cow::Owned(format!(
            "derive_more-generated `{}` is called without an established variant",
            self.method
        ))
    }

    fn rationale_message(&self) -> Cow<'_, str> {
        Cow::Borrowed("the generated accessor panics whenever the receiver has another variant")
    }

    fn remediation_message(&self) -> Cow<'_, str> {
        Cow::Borrowed(
            "pattern-match the receiver or use a derive_more `TryUnwrap` accessor for a fallible extraction",
        )
    }

    fn emit(self, cx: &LateContext<'_>) {
        cx.emit_span_lint(
            DERIVE_MORE_PANIC_PRONE_DERIVED_VARIANT_ACCESSORS,
            self.span,
            DiagDecorator(|diag| {
                diag.primary_message(self.primary_message().into_owned());
                diag.span_label(self.span, "this call can panic on another variant");
                diag.note(self.rationale_message().into_owned());
                diag.help(self.remediation_message().into_owned());
            }),
        );
    }
}

// -----------------------------------------------------------------------------
// DeriveMorePanicProneDerivedVariantAccessors: Fallible accessor policy
// -----------------------------------------------------------------------------

/// Finds generated variant accessors called without a statically proven matching variant.
struct DeriveMorePanicProneDerivedVariantAccessors;

crate::impl_late_lint! {
    #[doc = include_str!("README.md")]
    pub DERIVE_MORE_PANIC_PRONE_DERIVED_VARIANT_ACCESSORS,
    Warn,
    "finds unchecked calls to derive_more-generated variant unwrap accessors",
    DeriveMorePanicProneDerivedVariantAccessors
}

impl DeriveMorePanicProneDerivedVariantAccessors {
    /// Returns whether a method was generated by `derive_more`'s unwrap machinery.
    fn is_derive_more_unwrap(cx: &LateContext<'_>, target: DefId) -> bool {
        cx.tcx.def_span(target).macro_backtrace().any(|expansion| {
            expansion.macro_def_id.is_some_and(|definition| {
                cx.tcx.crate_name(definition.krate).as_str() == "derive_more_impl"
                    && cx.tcx.item_name(definition).as_str() == "Unwrap"
            })
        })
    }

    /// Removes authored wrappers that do not change the constructed value.
    const fn peel_transparent<'hir>(mut expression: &'hir Expr<'hir>) -> &'hir Expr<'hir> {
        loop {
            expression = match expression.kind {
                ExprKind::Block(block, None) if block.stmts.is_empty() => {
                    // An empty block without a tail value cannot expose a construction expression.
                    let Some(inner) = block.expr else {
                        return expression;
                    };
                    inner
                }
                ExprKind::DropTemps(inner) => inner,
                _ => return expression,
            };
        }
    }

    /// Resolves the enum variant constructed directly by an expression.
    fn constructed_variant(cx: &LateContext<'_>, receiver: &Expr<'_>) -> Option<DefId> {
        let receiver = Self::peel_transparent(receiver);
        let resolution = match receiver.kind {
            ExprKind::Call(constructor, _) => {
                // Indirect constructor calls cannot identify one enum variant statically.
                let ExprKind::Path(path) = constructor.kind else {
                    return None;
                };
                cx.qpath_res(&path, constructor.hir_id)
            }
            ExprKind::Struct(path, ..) => cx.qpath_res(path, receiver.hir_id),
            ExprKind::Path(path) => cx.qpath_res(&path, receiver.hir_id),
            // Other receiver expressions do not construct a statically known variant directly.
            _ => return None,
        };

        match resolution {
            Res::Def(DefKind::Ctor(CtorOf::Variant, _), constructor) => {
                Some(cx.tcx.parent(constructor))
            }
            Res::Def(DefKind::Variant, variant) => Some(variant),
            _ => None,
        }
    }

    /// Proves that the receiver is constructed as the variant required by the accessor.
    fn is_receiver_constructing_expected_variant(
        cx: &LateContext<'_>,
        receiver: &Expr<'_>,
        method: &str,
    ) -> bool {
        // Receivers without a direct variant construction cannot satisfy the accessor precondition.
        let Some(variant) = Self::constructed_variant(cx, receiver) else {
            return false;
        };

        let expected = format!(
            "unwrap_{}",
            cx.tcx.item_name(variant).as_str().to_case(Case::Snake)
        );
        method == expected
            || method == format!("{expected}_ref")
            || method == format!("{expected}_mut")
    }
}

impl LateLintPass<'_> for DeriveMorePanicProneDerivedVariantAccessors {
    fn check_expr(&mut self, cx: &LateContext<'_>, expression: &Expr<'_>) {
        // Generated calls are not authored unchecked accessor decisions.
        if expression.span.from_expansion() {
            return;
        }

        // Variant accessors must be expressed as receiver method calls.
        let ExprKind::MethodCall(segment, receiver, arguments, _) = expression.kind else {
            return;
        };

        // Retain only zero-argument unwrap-shaped accessors.
        if !arguments.is_empty() || !segment.ident.name.as_str().starts_with("unwrap_") {
            return;
        }

        // Unresolved methods cannot be matched to generated derive output.
        let Some(target) = cx
            .tcx
            .typeck(expression.hir_id.owner.def_id)
            .type_dependent_def_id(expression.hir_id)
        else {
            return;
        };

        // Manual methods with similar names are outside generated accessor policy.
        if !Self::is_derive_more_unwrap(cx, target) {
            return;
        }
        let method = segment.ident.name.to_string();

        // A directly matching variant construction satisfies the generated precondition.
        if Self::is_receiver_constructing_expected_variant(cx, receiver, &method) {
            return;
        }

        Violation {
            span: expression.span,
            method,
        }
        .emit(cx);
    }
}
