mod contracts;

pub mod serde_ambiguous_untagged_enums;
pub mod serde_asymmetric_serde_contracts;
pub mod serde_catch_all_variants_hiding_schema_drift;
pub mod serde_deserialization_bypassing_invariants;
pub mod serde_defaults_hiding_missing_data;
pub mod serde_duplicate_serialized_names;
pub mod serde_flattened_field_collisions;
pub mod serde_flattened_unknown_field_policies;
pub mod serde_format_specific_serde_impls;
pub mod serde_lossy_conditional_serialization;
pub mod serde_manual_deserialize_impls;
pub mod serde_manual_serialize_impls;
pub mod serde_non_roundtripping_serde_adapters;
pub mod serde_remote_representations_drifting_from_sources;
pub mod serde_sensitive_fields_serialized_by_default;
pub mod serde_unstable_implicit_wire_names;
