extern crate rustc_errors;
extern crate rustc_hir;
extern crate rustc_middle;
extern crate rustc_span;

use std::borrow::Cow;
use std::collections::{HashMap, HashSet};

use rustc_errors::DiagDecorator;
use rustc_hir::{ImplItem, ImplItemKind, Item, ItemKind, Node};
use rustc_lint::{LateContext, LateLintPass, LintContext};
use rustc_middle::ty;
use rustc_span::def_id::LocalDefId;
use rustc_span::{Span, sym};

use crate::utils::diagnostic::LateViolation;
use crate::utils::impl_target::ImplTargetExt;

// -----------------------------------------------------------------------------
// Violation: Manual structural builder protocol
// -----------------------------------------------------------------------------

/// Authored builder whose protocol can be generated by Bon.
struct Violation {
    /// Builder declaration receiving the diagnostic.
    span: Span,
    /// Builder type named in the diagnostic.
    name: String,
    /// Consuming setters that reproduce Bon's generated protocol.
    setters: usize,
}

impl LateViolation for Violation {
    fn primary_message(&self) -> Cow<'_, str> {
        Cow::Owned(format!(
            "manual builder `{}` has a Bon-compatible structural protocol",
            self.name
        ))
    }

    fn rationale_message(&self) -> Cow<'_, str> {
        Cow::Owned(format!(
            "its start method, {} consuming setters, and infallible terminal method reproduce generated builder mechanics",
            self.setters
        ))
    }

    fn remediation_message(&self) -> Cow<'_, str> {
        Cow::Borrowed(
            "derive `bon::Builder` for structural construction, or put `#[builder]` on the domain constructor when it owns policy",
        )
    }

    fn emit(self, cx: &LateContext<'_>) {
        cx.emit_span_lint(
            BON_MANUAL_BUILDER_IMPLEMENTATIONS,
            self.span,
            DiagDecorator(|diag| {
                diag.primary_message(self.primary_message().into_owned());
                diag.span_label(
                    self.span,
                    "this authored type duplicates Bon's builder protocol",
                );
                diag.note(self.rationale_message().into_owned());
                diag.help(self.remediation_message().into_owned());
            }),
        );
    }
}

// -----------------------------------------------------------------------------
// Candidate: Manual builder protocol evidence
// -----------------------------------------------------------------------------

/// Structural type and method roles collected before reporting.
#[derive(Default)]
struct Candidate {
    /// Candidate builder declaration.
    span: Span,
    /// Authored builder type name.
    name: String,
    /// Named state fields expected to have corresponding setters.
    fields: HashSet<String>,
    /// Whether an associated `new` starts construction.
    has_start: bool,
    /// Distinct field-named consuming setters.
    setters: HashSet<String>,
    /// Whether an infallible terminal method completes construction.
    has_terminal: bool,
}

// -----------------------------------------------------------------------------
// BonManualBuilderImplementations: Derivable builder policy
// -----------------------------------------------------------------------------

/// Correlates builder-shaped types with their start, setter, and finish methods.
#[derive(Default)]
struct BonManualBuilderImplementations {
    /// Builder-shaped types indexed by their definitions.
    candidates: HashMap<LocalDefId, Candidate>,
}

dylint_linting::impl_late_lint! {
    #[doc = include_str!("README.md")]
    pub BON_MANUAL_BUILDER_IMPLEMENTATIONS,
    Warn,
    "finds manual structural builders reproducible by Bon",
    BonManualBuilderImplementations::default()
}

impl BonManualBuilderImplementations {
    /// Minimum structural fields and setters that establish a builder protocol.
    const MINIMUM_STRUCTURAL_MEMBERS: usize = 2;

    /// Returns whether a terminal result still communicates domain failure.
    fn is_fallible(cx: &LateContext<'_>, ty: ty::Ty<'_>) -> bool {
        matches!(ty.kind(), ty::Adt(definition, _) if cx.tcx.is_diagnostic_item(sym::Result, definition.did()) || cx.tcx.is_diagnostic_item(sym::Option, definition.did()))
    }
}
impl LateLintPass<'_> for BonManualBuilderImplementations {
    fn check_item(&mut self, _cx: &LateContext<'_>, item: &Item<'_>) {
        // Only structs can establish the field-backed protocol of a manual builder.
        let ItemKind::Struct(identifier, _, data) = item.kind else {
            return;
        };
        let name = identifier.name.as_str();

        // Generated, conventionally unrelated, or trivial structs are not builder candidates.
        if item.span.from_expansion()
            || !name.ends_with("Builder")
            || data.fields().len() < Self::MINIMUM_STRUCTURAL_MEMBERS
        {
            return;
        }

        self.candidates.insert(
            item.owner_id.def_id,
            Candidate {
                span: identifier.span,
                name: name.to_owned(),
                fields: data
                    .fields()
                    .iter()
                    .map(|field| field.ident.name.to_string())
                    .collect(),
                ..Candidate::default()
            },
        );
    }

    fn check_impl_item(&mut self, cx: &LateContext<'_>, item: &ImplItem<'_>) {
        // Only methods can contribute setters or a terminal builder operation.
        let ImplItemKind::Fn(signature, _) = item.kind else {
            return;
        };

        // Generated methods do not represent an authored manual builder protocol.
        if item.span.from_expansion() {
            return;
        }
        let implementation = cx.tcx.local_parent(item.owner_id.def_id);

        // Associated functions without an item parent cannot belong to an inspectable impl.
        let Node::Item(parent) = cx.tcx.hir_node_by_def_id(implementation) else {
            return;
        };

        // Only direct struct implementations can contribute to a recorded builder candidate.
        let Some(definition) = parent.direct_struct(cx) else {
            return;
        };

        // Methods on structs rejected during candidate discovery need no protocol analysis.
        let Some(candidate) = self.candidates.get_mut(&definition) else {
            return;
        };

        let function = cx
            .tcx
            .fn_sig(item.owner_id.def_id)
            .instantiate_identity()
            .skip_binder();
        let output_is_builder = matches!(function.output().kind(), ty::Adt(adt, _) if adt.did() == definition.to_def_id());

        let receiver_is_builder = function
            .inputs()
            .first()
            .is_some_and(|receiver| matches!(receiver.kind(), ty::Adt(adt, _) if adt.did() == definition.to_def_id()));
        let name = item.ident.name.as_str();

        // Classify the method by its role in a conventional builder protocol.
        if !signature.decl.implicit_self.has_implicit_self() {
            candidate.has_start |=
                name == "new" && function.inputs().is_empty() && output_is_builder;
        } else if receiver_is_builder
            && function.inputs().len() == 2
            && output_is_builder
            && candidate.fields.contains(name)
        {
            candidate.setters.insert(name.to_owned());
        } else if receiver_is_builder
            && function.inputs().len() == 1
            && matches!(name, "build" | "complete" | "finish")
            && !output_is_builder
            && !Self::is_fallible(cx, function.output())
            && matches!(function.output().kind(), ty::Adt(..))
        {
            candidate.has_terminal = true;
        }
    }

    fn check_crate_post(&mut self, cx: &LateContext<'_>) {
        for candidate in self.candidates.values() {
            if !(candidate.has_start
                && candidate.has_terminal
                && candidate.setters.len() >= Self::MINIMUM_STRUCTURAL_MEMBERS
                && candidate.setters.len() >= candidate.fields.len())
            {
                continue;
            }

            Violation {
                span: candidate.span,
                name: candidate.name.clone(),
                setters: candidate.setters.len(),
            }
            .emit(cx);
        }
    }
}
